#!/usr/bin/env bash
#------------------------{ Dev info }-----------------------------------------------------------------------------------
#Created by: Ivan Marov <ie.marov@gmail.com>
#Source: https://github.com/vaniacer/piu-piu-SH
# check bash version
case ${BASH_VERSINFO[@]::2} in [1-3]' '[0-9][0-9]|[1-3]' '[0-9]|'4 '[0-1])
    echo -e "\nYour BASH is too short!) 4.2+ required to run this game, your is - ${BASH_VERSINFO[@]}"
    exit 1;;
esac
#--------------------------------------------------------------------+
#Color picker, usage: printf $BLD$CUR$RED$BBLU'Hello World!'$DEF     |
#-------------------------+--------------------------------+---------+
#       Text color        |       Background color         |         |
#-----------+-------------+--------------+-----------------+         |
# Base color|Lighter shade| Base color   | Lighter shade   |         |
#-----------+-------------+--------------+-----------------+         |
BLK='\e[30m'; blk='\e[90m'; BBLK='\e[40m'; bblk='\e[100m' #| Black   |
RED='\e[31m'; red='\e[91m'; BRED='\e[41m'; bred='\e[101m' #| Red     |
GRN='\e[32m'; grn='\e[92m'; BGRN='\e[42m'; bgrn='\e[102m' #| Green   |
YLW='\e[33m'; ylw='\e[93m'; BYLW='\e[43m'; bylw='\e[103m' #| Yellow  |
BLU='\e[34m'; blu='\e[94m'; BBLU='\e[44m'; bblu='\e[104m' #| Blue    |
MGN='\e[35m'; mgn='\e[95m'; BMGN='\e[45m'; bmgn='\e[105m' #| Magenta |
CYN='\e[36m'; cyn='\e[96m'; BCYN='\e[46m'; bcyn='\e[106m' #| Cyan    |
WHT='\e[37m'; wht='\e[97m'; BWHT='\e[47m'; bwht='\e[107m' #| White   |
#-------------------------{ Effects }----------------------+---------+
DEF='\e[0m'   #Default color and effects                             |
BLD='\e[1m'   #Bold\brighter                                         |
DIM='\e[2m'   #Dim\darker                                            |
CUR='\e[3m'   #Italic font                                           |
UND='\e[4m'   #Underline                                             |
INV='\e[7m'   #Inverted                                              |
COF='\e[?25l' #Cursor Off                                            |
CON='\e[?25h' #Cursor On                                             |
#------------------------{ Functions }-------------------------------+
# Text positioning, usage: XY 10 10 'Hello World!'                   |
XY () { printf "\e[$2;${1}H$3"; }                                   #|
# Print line, usage: line - 10 | line -= 20 | line 'Hello World!' 20 |
line () { printf -v _L %$2s; printf -- "${_L// /$1}"; }             #|
# Create sequence like {0..(X-1)}                                    |
que () { printf -v _N %$1s; _N=(${_N// / 1}); printf "${!_N[*]}"; } #|
#----{ Start opt }------------------------------------{ description  }---------------------{ def. values }--------------
  background=true                                     # background objects visibility             (true)
     enumber=0                                        # current enemy counter                     (0)
       enmax=100                                      # max number of akiens                      (10)
       month=$(date +'%m')                            # get current month
        life=3                                        # life counter                              (3)
        ammo=100                                      # ammo counter                              (100)
         DHC=$BLK                                     # default hero color                        ($BLK)
         DSC=$RED                                     # default symbol color                      ($RED)
         DHS=★                                        # default symbol                            (★)
         spd=0.0001                                   # game\read speed                           (0.0001)
         MSN=1111                                     # messanger randomizer                      (1111)
          LX=1                                        # grass X counter
          ad='Die alien scum!'                        # ad plane message                          'Die alien scum!'
           G=1                                        # gun                                       (1)(max 5)
[[ -e ~/.piuconf ]] && . ~/.piuconf
. ./messages  #_MESSAGES_
. ./sprites   #_SPRITES_
. ./functions #_FUNCTIONS_
#======================================{ Main game loop single or server team mode }====================================
game () {
    while true; do
        #-{ Empty screen, count fps, set timings}------------------------------
        [[ $M -ge 10 ]] && M=0 || ((M++)) # enemies born rate
        screen=; fps_counter
        ENM=("${ENM[@]}")
        HER=("${HER[@]}")
        BP1=("${BP1[@]}")
        BP2=("${BP2[@]}")
        BP3=("${BP3[@]}")
        [[ $background ]] && add_backgound

        #-{ Add aliens }-------------------------------------------------------
        [[ $enumber -lt $enmax && $M -eq 0 ]] && {
            ENM+=("alien $endx $[RANDOM%enmyendy+3] 3 5 0 $[RANDOM%2] 1 0 $[RANDOM%3] 3")
            ((enumber++))
        }

        #-{ Print FPS }--------------------------------------------------------
        screen+="\e[$endy;2H${DEF}FPS:$RED$FPS ${DEF}max:$RED$FPSM ${DEF}low:$RED$FPSL ${DEF}avg:$RED$FPSA "

        #-{ Move bitplans }----------------------------------------------------
        for i in ${!BP1[@]}; { OI=(${BP1[i]}); get_obj_data; }
        for i in ${!BP2[@]}; { OI=(${BP2[i]}); get_obj_data; }
        for i in ${!HER[@]}; { OI=(${HER[i]}); get_obj_data; }
        for i in ${!ENM[@]}; { OI=(${ENM[i]}); get_obj_data; }
        for i in ${!BP3[@]}; { OI=(${BP3[i]}); get_obj_data; }

        #-{ Print everything }-------------------------------------------------
        printf "$screen"
    done
}
#=================================================={ Initialisation }===================================================
trap : ALRM
trap bye INT TERM SIGINT SIGTERM EXIT
get_dimensions; stty -echo; printf "$COF"; clear
H1C=${DHC}; S1C=${DSC}; H1S=${DHS};
#-{ Generate grass }-----------------------------------------------------------
for ((i=0; i<$endx; i++)); do land+=${grass[$[RANDOM % ${#grass[*]}]]}; done; land+=$land; LN=${#land}
fill_screen
H1X=10 H1Y=10 HER[0]="hero1 6 14 $H1X $H1Y 0 0 1 15 0 3"
game
