#!/bin/bash
#================================================{ Sprites }============================================================
case $month in
    0[1-4]|12)
        SKY=$DEF$bwht         # winter & early spring sky
        LND=$DEF$BLD$WHT$BWHT # winter & early spring land
        CLD=30                # winter & early spring clouds rnd
        TRE=50;;              # winter & early spring trees rnd

    0[5-8]   )
        SKY=$DEF$bcyn         # late spring & summer sky
        LND=$DEF$DIM$GRN$bgrn # late spring & summer land
        CLD=50                # late spring & summer clouds rnd
        TRE=20;;              # late spring & summer trees rnd

    09|1[0-1])
        SKY=$DEF$BCYN         # autumn sky
        LND=$DEF$DIM$YLW$BGRN # autumn land
        CLD=20                # autumn clouds rnd
        TRE=50;;              # autumn trees rnd
esac
gun=(─ ─ ═ ≡ ≣ 𝄚)
grass=(│ ' ' ║ ' ' ░ ' ' ▒ ' ' ▓ ' ' █)    # grass types
#------------------------{ Hero1 }--------------------------------------------------------------------------------------
mainrotor=(" ${blk}_   ${blk}_   ${blk}_   ${blk}_  ${blk}_ ${blk}_ ${blk}_  ${blk}_   ${blk}_   ${blk}_   ${blk}_$SKY"
           "_Z_ _Z_ _Z_ _Z_ ${blk}_ ${blk}_ ${blk}_ _Z_ _Z_ _Z_ _Z_$SKY"
           "_Z_ _Z_ _Z_ _Z_ _Z_ ${blk}_ _Z_ _Z_ _Z_ _Z_ _Z_$SKY"
           "_Z_ _Z_ _Z_ _Z_ ${blk}_ ${blk}_ ${blk}_ _Z_ _Z_ _Z_ _Z_$SKY")
tailrotor=("${blk}"'\\' "${blk}─" "${blk}/" "${blk}|")
sprite_hero1 () {
    server_read
    mov && HER[i]="hero1 $H1X $H1Y 6 14 $SC $SM $CS $CL $AS $AL"
    CM1=$SKY$H1C$BLD CM2=$SKY$DIM$H1C CM3=$SKY$H1C CM4=$SKY$BLD$H1C$UND
    X1="\\e[$[H1Y+5];$[H1X+7]H"
    re="n $[H1X+13] $[H1Y+2] .*|n $[H1X+12] $[H1Y+2] .*|n $[H1X+12] $[H1Y+1] .*|n $[H1X+11] $[H1Y+1] .*"
    [[ ${ENM[@]} =~ $re ]] && { T=($BASH_REMATCH); e=${T[@]:11:1}; x=${T[@]:1:1}; y=${T[@]:2:1}; unset ENM[e]; boom $x $y; BOOM $H1X $H1Y; }
    #0123456789ABCDEF
    #1              
    #2 __ ___________
    #3 |X\___.-╨─｡_
    #4 `─´‾‾‷\°★ º¯]─
    #5        ‾‾‾‾‾
    #6
    #                               1   2                          3          4         5         6         7         8          9         A         B         C         D          E    F
    cut "\\e[$H1Y;${H1X}H$SKY"     ' ' ' '                        ' '        ' '       ' '       ' '       ' '       ' '        ' '       ' '       ' '       ' '       ' '        ' '  ' '                    #1   
    cut "\\e[$[H1Y+1];${H1X}H$CM3" ' ' '_'                        '_'        ' '                                          ${mainrotor[AS]}                                                                     #2
    cut "\\e[$[H1Y+2];${H1X}H$CM2" ' ' '|' ${tailrotor[AS]} "$CM1"'\\' "$CM1"'_' "$CM1"'_' "$CM1"'_' "$CM3"'.' "$CM3"'-'  "$CM3"'╨' "$CM4"'─' "$CM4"'｡' "$CM1"'_' "$SKY"' '  "$SKY"' '                         #3
    cut "\\e[$[H1Y+3];${H1X}H$CM2" ' ' '`'                        '─'        '´'       '‾'       '‾'       '‷'       '\\' "$blk"'°' "$S1C"'★' "$SKY"' ' "$blk"'º' "$blk"'¯'  "$CM1"']'  $SKY$BLK${gun[$G]}$SKY #4
    cut "\\e[$[H1Y+4];${H1X}H$CM2" ' ' ' '                        ' '        ' '       ' '       ' '       ' '       ' '        '‾'       '‾'       '‾'       '‾'       '‾'  "$SKY"' '  ' '                    #5
    cut "\\e[$[H1Y+5];${H1X}H$SKY" ''  ''                         ''         ''        ''        ''        ''   "$X1"' '        ' '       ' '       ' '       ' '       ' '        ' '                         #6
}
#------------------------{ Ad plane }-----------------------------------------------------------------------------------
flame1=("$red-"       "$ylw~"       "$red- $RED~" "$ylw-")
flame2=("$ylw-"       "$red- $RED~" "$red~"       "$YLW~")
flame3=("$red- $RED~" "$red~"       "$YLW~"       "$ylw-")
for ((i=0; i<${#ad}; i++)); do ad_new+="$BLD$red${ad:$i:1} "; done
new_ad=( ${ad_new//  /_Z_ } ) line=( ${new_ad[@]//*/$blk-} ) width=$((19+${#new_ad[@]}))
sprite_msngr () {
    mov && BP2[i]="msngr $OX $OY 4 $width $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
    CM1=$SKY$BLD$blk CM2=$SKY$DIM$blk CM3=$SKY$blk
    X1="\\e[$OY;$[OX+7]H"     X2="\\e[$[OY+1];$[OX+1]H" X3="\\e[$[OY+1];$[OX+12]H"
    X4="\\e[$[OY+3];$[OX+4]H" X5="\\e[$[OY+3];$[OX+12]H"
    #0123456789ABCD...
    #1       __
    #2 _____/_/   +--------------------+~
    #3(°_\ |_)---<| Die alien scum DIE! -~
    #4    \|      +--------------------~
    #                            1          2   3         4       5         6          7         8   9   A   B   C       D   E   F  ...
    cut "\\e[$OY;${SX}H$CM1"     ''        ''  ''        ''      ''         ''        ''   "$X1"'_' '_'                                                                #1
    cut "\\e[$[OY+1];${SX}H$CM2" ''   "$X2"'_' '_'       '_'     '_'        '_'       '/'       '_' '/' ' ' ''  '' "$X3"'+' '-' '-' ${line[@]} ${flame1[AS]}       ' ' #2
    cut "\\e[$[OY+2];${SX}H$CM1" '(' "$UND"'°' ' ' "$CM2"'\\'    ' '  "$CM3"'|' "$UND"' ' "$CM3"')' '-' '-' '-' '<'     '|' ' ' ${new_ad[@]} ' ' $SKY${flame2[AS]} ' ' #3
    cut "\\e[$[OY+3];${SX}H$CM2" ''        ''  ''        '' "$X4"'\\' "$CM3"'|'       ' '       ''  ''  ''  ''  '' "$X5"'+' ${line[@]} ${flame3[AS]}               ' ' #4
}

#------------------------{ Aliens }-------------------------------------------------------------------------------------
CM1=$SKY$DIM$BLK CM2=$BLD$BLK
small=("${SKY}_Z_  ${SKY}_Z_  ${RED}o$CM1"
       "${SKY}_Z_  ${RED}o    ${SKY}_Z_$CM1"
       "${RED}o    ${SKY}_Z_  ${SKY}_Z_$CM1"
       "${SKY}_Z_  ${SKY}_Z_  ${SKY}_Z_$CM1")

CM1=$SKY$BLD$ylw CM2=$SKY$UND$BLD$grn
pumtop=( "$CM2"'\\'"$CM1" "$CM2"'\\'"$CM1" "$CM2|$CM1" "$CM2|$CM1" "$CM2/$CM1" "$CM2/$CM1")
pumface=("${RED}O ${RED}… ${RED}o$CM1"
         "${RED}… ${RED}o _Z_$CM1"
         "${RED}o _Z_     ${RED}O$CM1"
         "_Z_     _Z_     _Z_$CM1"
         "_Z_     _Z_     ${RED}O$CM1"
         "_Z_     ${RED}O ${RED}…$CM1")

sprite_alien () {
    case "$day$month" in
        3110)
        mov && ENM[i]="alien $OX $OY 3 5 $SC $SM $CS $CL $AS 5 $i" || { unset ENM[i]; ((enumber--)); return; }
        X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
        CM1=$SKY$BLD$ylw CM2=$SKY$UND$DIM$grn CM3=$SKY$ylw
        #012345
        #1 _\_
        #2(O…o)
        #3 `¯´
        #                            1        2   3             4   5
        cut "\\e[$OY;${SX}H$CM1"     '' "$X1"'_' ${pumtop[AS]} '_'      #1
        cut "\\e[$[OY+1];${SX}H$CM1" '('         ${pumface[AS]}    ')'  #2
        cut "\\e[$[OY+2];${SX}H$CM1" '' "$X2"'`' '¯'           '´';;    #3

        *)
        mov && ENM[i]="alien $OX $OY 3 5 $SC $SM $CS $CL $AS 3 $i" || { unset ENM[i]; ((enumber--)); return; }
        X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
        CM1=$SKY$DIM$BLK CM2=$BLD$BLK
        #012345
        #1 ___
        #2( o )
        #3 `¯´
        #                            1        2         3         4   5
        cut "\\e[$OY;${SX}H$CM1"     '' "$X1"'_' "$CM2"'_' "$CM1"'_'      #1
        cut "\\e[$[OY+1];${SX}H$CM1" '('       ${small[AS]}   ')'         #2
        cut "\\e[$[OY+2];${SX}H$CM1" '' "$X2"'`'       '¯'       '´';;    #3
    esac
}

#------------------------{ Clouds }-------------------------------------------------------------------------------------
case $month in
    0[1-4]|12) C1C=$SKY$DIM$CYN;; # winter & early spring
    0[5-8]   ) C1C=$SKY$DIM$WHT;; # late spring & summer
    09|1[0-1]) C1C=$SKY$blk    ;; # autumn
esac
sprite_cloud1 () {
    mov && BP1[i]="cloud1 $OX $OY 3 6 $SC $SM $CS $CL $AS $AL" || { unset BP1[i]; return; }
    X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
    #0123456
    #1 ,-+.
    #2(    )
    #3 `+-´
    #                              1        2   3   4   5   6
    cut "\\e[$OY;${SX}H$C1C"       '' "$X1"',' '-' '+' '.'     #1
    cut "\\e[$[$OY+1];${SX}H$C1C"  '('     ' ' ' ' ' ' ' ' ')' #2
    cut "\\e[$[$OY+2];${SX}H$C1C"  '' "$X2"'`' '+' '-' '´'     #3
}

case $month in
    0[1-4]|12) C2C=$SKY$CYN;; # winter & early spring
    0[5-8]   ) C2C=$SKY$WHT;; # late spring & summer
    09|1[0-1]) C2C=$SKY$BLK;; # autumn
esac
sprite_cloud2 () {
    mov && BP2[i]="cloud2 $OX $OY 3 8 $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
    X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
    #012345678
    #1 ,-._..
    #2(      )
    #3 `-...´
    #                              1        2   3   4   5   6   7   8
    cut "\\e[$OY;${SX}H$C2C"       '' "$X1"',' '-' '.' '_' '.' '.'     #1   
    cut "\\e[$[$OY+1];${SX}H$C2C"  '('     ' ' ' ' ' ' ' ' ' ' ' ' ')' #2
    cut "\\e[$[$OY+2];${SX}H$C2C"  '' "$X2"'`' '-' '.' '.' '.' '´'     #3
}

case $month in
    0[1-4]|12) C3C=$SKY$BLD$CYN;; # winter & early spring
    0[5-8]   ) C3C=$SKY$BLD$WHT;; # late spring & summer
    09|1[0-1]) C3C=$SKY$DIM$BLK;; # autumn
esac
sprite_cloud3 () {
    mov && BP3[i]="cloud3 $OX $OY 3 11 $SC $SM $CS $CL $AS $AL" || { unset BP3[i]; return; }
    X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
    #0123456789AB
    #1 ,+¯`.-¯`.
    #2(         )
    #3 `--.,,.-´
    #                              1        2   3   4   5   6   7   8   9   A   B
    cut "\\e[$OY;${SX}H$C3C"       '' "$X1"',' '+' '¯' '`' '.' '-' '¯' '`' '.'     #1
    cut "\\e[$[$OY+1];${SX}H$C3C"  '('     ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ')' #2
    cut "\\e[$[$OY+2];${SX}H$C3C"  '' "$X2"'`' '-' '-' '.' ',' ',' '.' '-' '´'     #3
}

#------------------------{ Trees }--------------------------------------------------------------------------------------
case $month in
    0[1-4]|12) T1C=$SKY$DIM$WHT tree1H=3;; # winter & early spring
    0[5-8]   ) T1C=$SKY$DIM$GRN tree1H=4;; # late spring & summer
    09|1[0-1]) T1C=$SKY$DIM$YLW tree1H=4;; # autumn
esac
sprite_tree1 () {
    case $month in
        0[1-4]|12)
        mov && BP1[i]="tree1 $OX $OY 3 2 $SC $SM $CS $CL $AS $AL" || { unset BP1[i]; return; }
        X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H" CM1="$DIM$blk"
        #0123
        #1 |/
        #2\|
        #3 |
        #                              1           2      3
        cut "\\e[$OY;${SX}H$T1C"       ''    "$X1"'|'    '/'  #1
        cut "\\e[$[$OY+1];${SX}H$T1C"  '\\' "$CM1"'|'         #2
        cut "\\e[$[$OY+2];${SX}H$CM1"  ''    "$X2"'|';;       #3

        *)
        mov && BP1[i]="tree1 $OX $OY 4 2 $SC $SM $CS $CL $AS $AL" || { unset BP1[i]; return; }
        X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+3];$[OX+1]H" CM1="$DIM$blk"
        #0123
        #1 _
        #2/ \
        #3\|/
        #4 |
        #                               1            2         3
        cut "\\e[$OY;${SX}H$T1C"       ''      "$X1"'_'            #1
        cut "\\e[$[$OY+1];${SX}H$T1C"  '/'          ' '       '\\' #2
        cut "\\e[$[$OY+2];${SX}H$T1C"  '\\'   "$CM1"'|' "$T1C"'/'  #3
        cut "\\e[$[$OY+3];${SX}H$T1C"  ''  "$X2$CM1"'|';;          #4
    esac
}

case $month in
    0[1-4]|12) T2C=$SKY$WHT tree2H=5;; # winter & early spring
    0[5-8]   ) T2C=$SKY$GRN tree2H=6;; # late spring & summer
    09|1[0-1]) T2C=$SKY$YLW tree2H=6;; # autumn
esac
sprite_tree2 () {
    case $month in
        0[1-4]|12)
        mov && BP2[i]="tree2 $OX $OY 5 5 $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
        X1="\\e[$OY;$[OX+3]H" X2="\\e[$[OY+2];$[OX+1]H" X3="\\e[$[OY+3];$[OX+2]H" X4="\\e[$[OY+4];$[OX+2]H"
        #012345
        #1   |_
        #2\||/
        #3 \║|_
        #4  ║/
        #5  ║
        #                              1         2          3         4   5
        cut "\\e[$OY;${SX}H$T2C"       ''       ''         ''   "$X1"'|' '_'  #1
        cut "\\e[$[$OY+1];${SX}H$T2C"  '\\'     '|'  "$blk"'|'       '/'      #2
        cut "\\e[$[$OY+2];${SX}H$blk"  ''  "$X2"'\\'       '║' "$T2C"'|' '_'  #3
        cut "\\e[$[$OY+3];${SX}H$blk"  ''  ''         "$X3"'║'       '/'      #4
        cut "\\e[$[$OY+4];${SX}H$blk"  ''  ''         "$X4"'║';;              #5

        *)
        mov && BP2[i]="tree2 $OX $OY 6 5 $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
        X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+3];$[OX+1]H" X3="\\e[$[OY+4];$[OX+2]H" X4="\\e[$[OY+5];$[OX+2]H"
        #012345
        #1 _._
        #2/   \
        #3\ | /
        #4 \║/\
        #5  ║_/
        #6  ║
        #                              1       2          3         4         5
        cut "\\e[$OY;${SX}H$T2C"      '' "$X1"'_'        '.'       '_'             #1
        cut "\\e[$[$OY+1];${SX}H$T2C" '/'     ' '        ' '       ' '       '\\'  #2
        cut "\\e[$[$OY+2];${SX}H$T2C" '\\'    ' '  "$blk"'|'       ' ' "$T2C"'/'   #3
        cut "\\e[$[$OY+3];${SX}H$T2C" '' "$X2"'\\' "$blk"'║' "$T2C"'/'       '\\'  #4
        cut "\\e[$[$OY+4];${SX}H$blk" ''      ''    "$X3"'║' "$T2C"'_'       '/'   #5
        cut "\\e[$[$OY+5];${SX}H$blk" ''      ''    "$X4"'║'  ;;
    esac
}

case $month in
    0[1-4]|12) T3C=$SKY$BLD$cyn tree3H=8;; # winter & early spring
    0[5-8]   ) T3C=$SKY$BLD$GRN tree3H=9;; # late spring & summer
    09|1[0-1]) T3C=$SKY$DIM$red tree3H=9;; # autumn
esac
sprite_tree3 () {
    case "$day$month" in
        2[1-9]12|3[0-1]12|0[1-9]01|1001)
        mov && BP3[i]="tree3 $OX $OY 8 12 $SC $SM $CS $CL $AS $AL" || { unset BP3[i]; return; }
        X1="\\e[$OY;$[OX+6]H"     X2="\\e[$[OY+1];$[OX+4]H" X3="\\e[$[OY+2];$[OX+4]H" X4="\\e[$[OY+3];$[OX+4]H"
        X5="\\e[$[OY+4];$[OX+2]H" X6="\\e[$[OY+5];$[OX+2]H" X7="\\e[$[OY+7];$[OX+6]H"
        #0123456789ABC
        #1      ★
        #2    _❅|●
        #3    -/○\❄-
        #4    ●/|\\○
        #5  _/❄/●\❅\
        #6  ○///|\❄\● 
        #7_/❅/●/|○\❅\-
        #8      ║
        #                             1   2            3         4           5         6         7         8          9          A          B    C
        cut "\\e[$OY;${SX}H$RED"      ''  ''          ''        ''          ''        ''   "$X1"'★'                                                 #1
        cut "\\e[$[$OY+1];${SX}H$GRN" ''  ''          ''        ''     "$X2"'_' "$cyn"'❅' "$GRN"'|' "$BLU"'●'                                       #2
        cut "\\e[$[$OY+2];${SX}H$GRN" ''  ''          ''        ''     "$X3"'-'       '/' "$YLW"'○' "$GRN"'\\'  "$CYN"'❄' "$GRN"'-'                 #3
        cut "\\e[$[$OY+3];${SX}H$GRN" ''  ''          ''        '' "$X4$RED"'●' "$GRN"'/'       '|'       '\\'       '\\' "$ylw"'○'                 #4
        cut "\\e[$[$OY+4];${SX}H$GRN" ''  ''     "$X5"'_'       '/'   "$cyn"'❄' "$GRN"'/' "$blu"'●' "$GRN"'\\'  "$cyn"'❅' "$GRN"'\\'                #5
        cut "\\e[$[$OY+5];${SX}H$GRN" ''  '' "$X6$red"'○' "$GRN"'/'         '/'       '/'       '|'       '\\'  "$CYN"'❄' "$GRN"'\\' "$RED"'●'      #6
        cut "\\e[$[$OY+6];${SX}H$GRN" '_' '/'   "$cyn"'❅' "$GRN"'/'   "$YLW"'●' "$GRN"'/'       '|' "$RED"'○'   "$GRN"'\\' "$cyn"'❅' "$GRN"'\\' '-' #7
        cut "\\e[$[$OY+7];${SX}H$BLK" ''  ''          ''        ''          ''        ''   "$X7"'║';;                                               #8

        0[1-4]|12)
        mov && BP3[i]="tree3 $OX $OY 8 9 $SC $SM $CS $CL $AS $AL" || { unset BP3[i]; return; }
        X1="\\e[$OY;$[OX+2]H"     X2="\\e[$[OY+1];$[OX+3]H" X3="\\e[$[OY+3];$[OX+1]H" X4="\\e[$[OY+4];$[OX+3]H"
        X5="\\e[$[OY+5];$[OX+4]H" X6="\\e[$[OY+6];$[OX+4]H" X7="\\e[$[OY+7];$[OX+4]H"
        #0123456789
        #1  \|
        #2   \| |_
        #3_\_ ║/
        #4 /\ ║ \/_
        #5   \║ /
        #6    ║/
        #7    ║
        #8    ║
        #                              1        2         3         4         5         6         7    8   9
        cut "\\e[$OY;${SX}H$T3C"      ''       ''   "$X1"'\\'      '|'                                        #1
        cut "\\e[$[$OY+1];${SX}H$BLK" ''       ''        ''   "$X2"'\\'      '|'       ' ' "$T3C"'|'  '_'     #2
        cut "\\e[$[$OY+2];${SX}H$T3C" '_'      '\\'      '_'       ' ' "$BLK"'║'       '/'                    #3
        cut "\\e[$[$OY+3];${SX}H$T3C" ''  "$X3"'/'       '\\'      ' ' "$BLK"'║' "$T3C"' '       '\\' '/' '_' #4
        cut "\\e[$[$OY+4];${SX}H$BLK" ''       ''        ''   "$X4"'\\'      '║'       ' '       '/'          #5
        cut "\\e[$[$OY+5];${SX}H$BLK" ''       ''        ''        ''   "$X5"'║'       '/'                    #6
        cut "\\e[$[$OY+6];${SX}H$BLK" ''       ''        ''        ''   "$X6"'║'                              #7
        cut "\\e[$[$OY+7];${SX}H$BLK" ''       ''        ''        ''   "$X7"'║';;                            #8

        *)
        mov && BP3[i]="tree3 $OX $OY 9 9 $SC $SM $CS $CL $AS $AL" || { unset B3[i]; return; }
        X1="\\e[$OY;$[OX+3]H"     X2="\\e[$[OY+1];$[OX+2]H" X3="\\e[$[OY+2];$[OX+1]H" X4="\\e[$[OY+5];$[OX+3]H"
        X5="\\e[$[OY+6];$[OX+4]H" X6="\\e[$[OY+7];$[OX+4]H" X7="\\e[$[OY+8];$[OX+4]H"
        #0123456789
        #1   _._
        #2  /   \
        #3 _\ | /
        #4/  \║/__
        #5\_\/║/  \
        #6   \║|/_/
        #7    ║/
        #8    ║
        #9    ║
        #                             1       2          3          4          5         6         7         8   9
        cut "\\e[$OY;${SX}H$T3C"      ''      ''        ''    "$X1"'_'        '.'       '_'                          #1
        cut "\\e[$[$OY+1];${SX}H$T3C" ''      ''   "$X2"'/'        ' '        ' '       ' '       '\\'               #2
        cut "\\e[$[$OY+2];${SX}H$T3C" '' "$X3"'_'       '\\'       ' '  "$BLK"'|'       ' ' "$T3C"'/'                #3
        cut "\\e[$[$OY+3];${SX}H$T3C" '/'     ' '       ' '        '\\' "$BLK"'║' "$T3C"'/'       '_'       '_'      #4
        cut "\\e[$[$OY+4];${SX}H$T3C" '\\'    '_' "$BLK"'\\' "$T3C"'/'  "$BLK"'║' "$T3C"'/'       ' '       ' ' '\\' #5
        cut "\\e[$[$OY+5];${SX}H$BLK" ' '     ' '       ' '   "$X4"'\\'       '║' "$T3C"'|' "$BLK"'/' "$T3C"'_' '/'  #6
        cut "\\e[$[$OY+6];${SX}H$BLK" ''      ''        ''         ''    "$X5"'║' '/'                                #7
        cut "\\e[$[$OY+7];${SX}H$BLK" ''      ''        ''         ''    "$X6"'║'                                    #8
        cut "\\e[$[$OY+8];${SX}H$BLK" ''      ''        ''         ''    "$X7"'║';;                                  #9
    esac
}
#------------------------{ BOOM }---------------------------------------------------------------------------------------
#    .-.
#   (   )
#    `-´
#   , - .
#  (     )
#   . _ .

#   ´ ¯ `
# (       )
#  +  _ .'
 
#  .     .
#
#-         -
#
# '   .   `
#     _
#    (_)
#
#    .-. 
#   (   )
#    `-´
#     _
#   -   + 
#  (     )
#   + _ -
#
#    - -
#  ´     `
# '       '
#  `  _  ´
#

boom0 () {
    cut "\e[$BY;$[BX+3]H$YLW"      '_'
    cut "\e[$[BY+1];$[BX+2]H$YLW" '(_)'
}

boom1 () {
    cut "\e[$BY;$[BX+2]H$RED"      '.-.'
    cut "\e[$[BY+1];$[BX+1]H$RED" '(   )'
    cut "\e[$[BY+2];$[BX+1]H$RED"  '`-´'
}

boom2 () {
    cut "\e[$[BY-1];$[BX+2]H$red"    '_'
    cut "\e[$BY;$[BX+1]H$red"      '-   +'
    cut "\e[$[BY+1];${BX}H$red"   '(     )'
    cut "\e[$[BY+2];$[BX+1]H$red"  '+ _ -'
}

boom3 () {
    cut "\e[$[BY-1];$[BX+1]H$DIM$RED"     '- -'
    cut "\e[$BY;${BX}H$DIM$RED"         '´     `'
    cut "\e[$[BY+1];$[BX-1]H$DIM$RED"  "'       '"
    cut "\e[$[BY+2];${BX}H$DIM$RED"     '`  _  ´'
}

boom4 () {
    cut "\e[$[BY-1];$[BX+1]H$SKY"     '   '
    cut "\e[$BY;${BX}H$SKY"         '       '
    cut "\e[$[BY+1];$[BX-1]H$SKY"  '         '
    cut "\e[$[BY+2];${BX}H$SKY"     '       '
}

#boom0 () {

#    cut "\e[$BY;$[BX+3]H$red"      '.-.'
#    cut "\e[$[BY+1];$[BX+2]H$red" '(   )'
#    cut "\e[$[BY+2];$[BX+3]H$red"  '`-´'
#}

#boom1 () {

#    cut "\e[$BY;$[BX+2]H$RED"      ', - .'
#    cut "\e[$[BY+1];$[BX+1]H$RED" '(     )'
#    cut "\e[$[BY+2];$[BX+2]H$RED"  '. _ .'
#}

#boom2 () {

#    cut "\e[$BY;$[BX+2]H$DIM$RED"       '´ ¯ `'
#    cut "\e[$[BY+1];${BX}H$DIM$RED"   '(       )'
#    cut "\e[$[BY+2];$[BX+1]H$DIM$RED"  "+  _ .'"
#}
#boom3 () {

#    cut "\e[$[BY-1];$[BX+1]H$RED"   '.     .'
#    cut "\e[$BY;$[BX+1]H$SKY"      '         '
#    cut "\e[$[BY+1];$[BX-1]H$red" '-         -'
#    cut "\e[$[BY+2];$[BX+1]H$SKY" '           '
#    cut "\e[$[BY+3];${BX}H$red"    "'   .   \`"
#}

#boom4 () {
#    #eraser
#    cut "\e[$[BY-1];$[BX+1]H$SKY"   '       '
#    cut "\e[$BY;$[BX+1]H$SKY"      '         '
#    cut "\e[$[BY+1];$[BX-1]H$SKY" '           '
#    cut "\e[$[BY+2];$[BX+1]H$SKY" '           '
#    cut "\e[$[BY+3];${BX}H$SKY"    '         '
#}

sprite_boom () {
    BX=$OX BY=$OY
    [[ $AS -ge $AL ]] && { unset BP3[i]; return; }
    boom$AS; mov; BP3[i]="boom $BX $BY 0 0 $SC $SM $CS $CL $AS $AL"
}

