#!/bin/bash
#================================================{ Sprites }============================================================
case $month in
    0[1-4]|12)
        SKY=$DEF$bwht         # winter & early spring sky
        LND=$DEF$BLD$WHT$BWHT # winter & early spring land
        CLD=30                # winter & early spring clouds rnd
        TRE=50;;              # winter & early spring trees rnd

    0[5-8]   )
        SKY=$DEF$bcyn         # late spring & summer sky
        LND=$DEF$DIM$GRN$bgrn # late spring & summer land
        CLD=50                # late spring & summer clouds rnd
        TRE=30;;              # late spring & summer trees rnd

    09|1[0-1])
        SKY=$DEF$BCYN         # autumn sky
        LND=$DEF$DIM$YLW$BGRN # autumn land
        CLD=20                # autumn clouds rnd
        TRE=50;;              # autumn trees rnd
esac
  gun=(─ ─ ═ ≡ ≣ 𝄚)
grass=(│ ' ' ║ ' ' ░ ' ' ▒ ' ' ▓ ' ' █) # grass types
#------------------------{ Hero1 }--------------------------------------------------------------------------------------
mainrotor=("${blk}_ ${blk}_ ${blk}_ ${blk}_ ${blk}_ ${blk}_ ${blk}_ ${blk}_ ${blk}_ ${blk}_ ${blk}_"  # '___________'
           "    _Z_     _Z_     _Z_     _Z_ ${blk}_ ${blk}_ ${blk}_     _Z_     _Z_     _Z_     _Z_"  # '    ___    '
           "    _Z_     _Z_     _Z_     _Z_     _Z_ ${blk}_     _Z_     _Z_     _Z_     _Z_     _Z_"  # '     _     '
           "    _Z_     _Z_     _Z_     _Z_ ${blk}_ ${blk}_ ${blk}_     _Z_     _Z_     _Z_     _Z_") # '    ___    '
tailrotor=("${blk}"'\\' "${blk}─" "${blk}/" "${blk}|") # '\' '─' '/' '|'
sprite_hero1 () {
    server_read
    mov - || mess 'lose'
    GN=$BLD$BLK${gun[$G]}; [[ $G -eq 5 ]] && GN=$BLD$BLK${gun[$G]}_Z_
    [[ $life -gt 0 ]] && { CS=1; CL=16; OX=$H1X; OY=$H1Y; } || { H1X=$SX; H1Y=$OY; }
    CM1=$SKY$H1C$BLD CM2=$SKY$DIM$H1C CM3=$SKY$H1C CM4=$SKY$BLD$H1C$UND TR=${tailrotor[AS]}
    X1="\\e[$[H1Y+5];$[OX+6]H"
    re="bfire ($[H1X+12]|$[H1X+13]) ($[H1Y+2]|$[H1Y+3]).*|alien ($[H1X+12]|$[H1X+13]) ($[H1Y+1]|$[H1Y+2]).*|(life|ammo|gunup) ($[H1X+12]|$[H1X+13]) ($[H1Y+1]|$[H1Y+2]|$[H1Y+3]|$[H1Y+4]).*"
    collision 1 "$re" && { BOOM $H1X $H1Y; ((life--)); }
    #0123456789ABCDEFG                                                                                                                          ___
    #1                                                 █▓▒░                                       ___                                         _/ o \_
    #2 __ ___________                                                 ___                        (  o)                                       /O   O  \
    #3 |X\___.-╨─｡_                         -=>                      ( o )                        `¯´            █▓▒░     ___               (   O    O)
    #4 `─´‾‾‷\°★ º¯]─         - >                              ->     `¯´                                                (o  )               `¯¯---¯¯´
    #5        ‾‾‾‾‾                                                                                                       `¯´
    #6                
    #############################  1   2   3       4        5       6       7       8        9       A        B       C       D       E   F   G  #0
    cut "\\e[$H1Y;${SX}H$SKY"     ' ' ' ' ' '     ' '      ' '     ' '     ' '     ' '      ' '     ' '      ' '     ' '     ' '     ' ' ' ' ' ' #1
    cut "\\e[$[H1Y+1];${SX}H$CM3" ' ' '_' '_'     ' '                                         ${mainrotor[AS]}                               ' ' #2
    cut "\\e[$[H1Y+2];${SX}H$CM2" ' ' '|' $TR $CM1'\\' $CM1'_' $CM1'_' $CM1'_' $CM3'.'  $CM3'-' $CM3'╨'  $CM4'─' $CM4'｡' $CM1'_' $SKY' ' ' ' ' ' #3
    cut "\\e[$[H1Y+3];${SX}H$CM2" ' ' '`' '─'     '´'      '‾'     '‾'     '‷'     '\\' $blk'°' $S1C$H1S $SKY' ' $blk'º' $blk'¯' $CM1']' $GN ' ' #4
    cut "\\e[$[H1Y+4];${SX}H$CM2" ' ' ' ' ' '     ' '      ' '     ' '     ' '     ' '      '‾'     '‾'      '‾'     '‾'     '‾' $SKY' ' ' ' ' ' #5
    cut "\\e[$[H1Y+5];${SX}H$SKY" ''  ''  ''      ''       ''      ''   $X1' '     ' '      ' '     ' '      ' '     ' '     ' '     ' '         #6
    [[ $C1 -gt 0  ]] && ((C1--))
    HER[i]="hero1 $OX $OY 6 14 $SC $SM $CS $CL $AS $AL $C1"
}
#------------------------{ Shoots }-------------------------------------------------------------------------------------
shoot1=(
    "_Z_           $RED-"  #  ->
    "$BLD$red- $BLD$red="  # -=>
    "$red=         $red-"  # =->
    "$RED-           _Z_") # - >
sprite_piu1 () {
    case "$day$month$virus" in
        *covid-19)
            mov + && PIU[i]="piu1 $OX $OY 1 3 $SC $SM $CS $CL $AS 3 $i" || { unset PIU[i]; return; }
            re="alien ($OX|$[OX+1]) $[OY-1].*|boss ($OX|$[OX+1]) ($[OY-2]|$[OY-3]|$[OY-4]).*"
            collision a "$re" $OX $[OY-1] && { unset PIU[i]; return; }
            #0123
            #1 ==
            ########################  1       2       3    #0
            cut "\\e[$OY;${OX}H$SKY" ' ' $RED'=' $BLU'=';; #1
        *)
            CM1=$SKY$BLD$GRN
            mov + && PIU[i]="piu1 $OX $OY 1 4 $SC $SM $CS $CL $AS 3 $i" || { unset PIU[i]; return; }
            re="alien ($OX|$[OX+1]) $[OY-1].*|boss ($OX|$[OX+1]) ($[OY-2]|$[OY-3]|$[OY-4]).*"
            collision a "$re" $OX $[OY-1] && { unset PIU[i]; return; }
            #01234
            #1 -=>
            ########################  1      2     3        4    #0
            cut "\\e[$OY;${OX}H$SKY" ' ' ${shoot1[AS]} $CM1'>';; #1
    esac
}

bshoot=('█ ▓ ▒ ░'
        '▓ ▒ ░ ▒'
        '▒ ░ ▒ ▓'
        '░ ▒ ▓ █'
        '▒ ▓ █ ▓'
        '▓ █ ▓ ▒')
sprite_bfire () {
    CM1=$SKY$BLD$ylw
    mov - && ENM[i]="bfire $OX $OY 1 5 $SC $SM $CS $CL $AS 5 $i" || { unset ENM[i]; return; }
    #012345
    #1█▓▒░ 
    ######################## 1   2   3   4  5  #0
    cut "\\e[$OY;${SX}H$CM1" ${bshoot[AS]} ' ' #1
}
#------------------------{ Aliens }-------------------------------------------------------------------------------------
small=("${SKY}_Z_  ${SKY}_Z_  ${RED}o"
       "${SKY}_Z_  ${RED}o    ${SKY}_Z_"
       "${RED}o    ${SKY}_Z_  ${SKY}_Z_"
       "${SKY}_Z_  ${SKY}_Z_  ${SKY}_Z_")

CM1=$SKY$UND$BLD$grn
pumtop=( "$CM1"'\\' "$CM1"'\\' "$CM1|" "$CM1|" "$CM1/" "$CM1/")
pumface=("${RED}O ${RED}… ${RED}o"
         "${RED}… ${RED}o _Z_"
         "${RED}o _Z_     ${RED}O"
         "_Z_     _Z_     _Z_$CM1"
         "_Z_     _Z_     ${RED}O"
         "_Z_     ${RED}O ${RED}…")

top1=("$RED." "$RED," "$RED'" "$RED'")
top2=("$RED'" "$RED'" "$RED." "$RED,")
mid1=("$RED-" "$RED+" "$RED'" "$RED'")
mid2=("$RED+" "$RED'" "$RED'" "$RED-")
bot1=($RED'´'  $RED'"' $RED'`' $RED'"')
bot2=($RED'"'  $RED'`' $RED'"' $RED'´')
cen=("$RED"o  "$RED+" "$RED*" "$RED+")

sprite_alien () {
    case "$day$month$virus" in
        3110)
            mov - && ENM[i]="alien $OX $OY 3 5 $SC $SM $CS $CL $AS 5 $i" || { unset ENM[i]; ((enumber--)); return; }
            X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
            CM1=$SKY$BLD$ylw CM2=$SKY$UND$DIM$grn CM3=$SKY$ylw
            #0123456
            #1 _\_  
            #2(O…o) 
            #3 `¯´  
            ############################  1     2        3            4   5   6  #0
            cut "\\e[$OY;${SX}H$CM1"     '' $X1'_' ${pumtop[AS]} $CM1'_' ' '     #1
            cut "\\e[$[OY+1];${SX}H$CM1" '('       ${pumface[AS]}  "$CM1"')' ' ' #2
            cut "\\e[$[OY+2];${SX}H$CM1" '' $X2'`'      '¯'          '´' ' ';;   #3

        *covid-19)
            mov - && ENM[i]="alien $OX $OY 3 5 $SC $SM $CS $CL $AS 3 $i" || { unset ENM[i]; ((enumber--)); return; }
            X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H" CM1=$SKY$DIM$BLK
            #0123456
            #1 ._,  
            #2-( )- 
            #3 ´‾`  
            ############################  1           2         3          4    5          6  #0
            cut "\\e[$OY;${SX}H$CM1"     '' $X1${top1[AS]} $CM1'_' ${top2[AS]} ' '            #1
            cut "\\e[$[OY+1];${SX}H$CM1" ${mid1[AS]} '(' ${cen[AS]} "$CM1"')' ${mid2[AS]} ' ' #2
            cut "\\e[$[OY+2];${SX}H$CM1" '' $X2${bot1[AS]} $CM1'‾' ${bot2[AS]} ' ';;          #3

        *)
            mov - && ENM[i]="alien $OX $OY 3 5 $SC $SM $CS $CL $AS 3 $i" || { unset ENM[i]; ((enumber--)); return; }
            X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
            CM1=$SKY$DIM$BLK CM2=$BLD$BLK
            #0123456
            #1 ___  
            #2( o ) 
            #3 `¯´  
            ############################  1     2       3       4    5   6  #0
            cut "\\e[$OY;${SX}H$CM1"     '' $X1'_' $CM2'_' $CM1'_'  ' '     #1
            cut "\\e[$[OY+1];${SX}H$CM1" '('     ${small[AS]} "$CM1"')' ' ' #2
            cut "\\e[$[OY+2];${SX}H$CM1" '' $X2'`'     '¯'     '´'  ' ';;   #3
    esac
}

big1=("_Z_     _Z_     ${YLW}O _Z_     _Z_     _Z_     ${YLW}O"
      "_Z_     _Z_     _Z_ $BLD${YLW}O _Z_     _Z_     _Z_"
      "${YLW}O _Z_     _Z_     _Z_     ${YLW}O _Z_     _Z_"
      "_Z_     ${YLW}O _Z_     _Z_     _Z_     ${YLW}O _Z_")

big2=("_Z_     ${BLU}O _Z_     _Z_     _Z_     ${BLU}O _Z_"
      "${BLU}O _Z_     _Z_     _Z_     ${BLU}O _Z_     _Z_"
      "_Z_     _Z_     _Z_ $BLU${BLD}O _Z_     _Z_     _Z_"
      "_Z_     _Z_     ${BLU}O _Z_     _Z_     _Z_     ${BLU}O")

big3=(" *   + "
      "+   *  "
      "   +   "
      "  *   +")

big4=("  *   +"
      "   *   "
      "*   +  "
      " +   * ")
mouthtop=("${RED}/ ${RED}V ${RED}V ${RED}V ${RED}V ${RED}V $RED"'\\'
          "${RED}/ ${RED}v ${RED}v ${RED}v ${RED}v ${RED}v $RED"'\\'
          "${RED}. ${RED}- ${RED}- ${RED}- ${RED}- ${RED}- ${RED}."
          "_Z_     _Z_     _Z_     _Z_     _Z_     _Z_     _Z_"
          "${RED}. ${RED}- ${RED}- ${RED}- ${RED}- ${RED}- ${RED}."
          "${RED}/ ${RED}v ${RED}v ${RED}v ${RED}v ${RED}v ${RED}"'\\'
          "${RED}/ ${RED}V ${RED}V ${RED}V ${RED}V ${RED}V ${RED}"'\\')

mouthlow=("${RED}V   ${RED}v ${RED}v ${RED}v ${RED}v ${RED}v ${RED}V"
          "${RED}V   ${RED}^ ${RED}^ ${RED}^ ${RED}^ ${RED}^ ${RED}V"
          ${RED}'`'" ${RED}¯ ${RED}¯ ${RED}¯ ${RED}¯ ${RED}¯ ${RED}´"
          "_Z_       ${RED}‾ ${RED}‾ ${RED}‾ ${RED}‾ ${RED}‾ _Z_"
          ${RED}'`'" ${RED}- ${RED}- ${RED}- ${RED}- ${RED}- ${RED}´"
          "${RED}V   ${RED}^ ${RED}^ ${RED}^ ${RED}^ ${RED}^ ${RED}V"
          "${RED}V   ${RED}v ${RED}v ${RED}v ${RED}v ${RED}v ${RED}V")

TX=$halfendx TY=$bossendy
sprite_boss () {
    [[ $H2Y ]] && HY=$[H2Y-1] || HY=$[H1Y-1] # kill client first
    if [[ $bhealth -gt 0 ]]; then
        #-{ Boss fire }--------------------------------------------------------
        [[ $OY -eq $HY && $C1 -eq 0 ]] && { ENM+=("bfire $[OX-4] $[OY+4] 1 5 0 0 1 5 $[RANDOM%5] 5 ${#ENM[@]}"); C1=20; }
        #-{ Boss move }--------------------------------------------------------
        [[ $OY -lt $HY ]] && ((OY++))
        [[ $OY -gt $HY ]] && ((OY--)) # this is a black magic
        [[ $OX -gt $TX ]] && mov - || { TX=$bossendx; SX=$OX; }
        [[ $OX -lt $TX ]] && mov + || { TX=$halfendx; SX=$OX; }
        #-{ Aliens out }-------------------------------------------------------
        EX=$[OX+2] EY=$[OY+5]; [[ $EY -gt $[enmyendy+3] ]] && EY=$[enmyendy+3]
    else # when boss' health goes to 0 it starts to fall, explodes and bounces on the ground
        AS=0; SM=3; mov - || mess 'win'
        [[ $OY -lt $TY ]] && ((OY++))  || { TY=$[bossendy-BJ]; ((BJ--)); }
        [[ $OY -gt $TY ]] && ((OY--))  ||   TY=$bossendy
        [[ $OX -gt -10 && $C1 -eq 0 ]] && { BOOM $OX $OY; C1=15; }
    fi
    [[ $C1 -gt 0 ]] && ((C1--))
    case "$day$month$virus" in
        3110)
            CM1=$SKY$BLD$ylw CM2=$BLD$RED EYE="$CM2( $CM2⁐ $CM2)"
            X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+1];$[OX+1]H" X3="\\e[$[OY+5];$[OX+1]H" X4="\\e[$[OY+6];$[OX+2]H"
            #0123456789ABCD
            #1             
            #2   .-./.-.   
            #3  /(_) (_)\  
            #4 ❲ /VVVVV\ ❳ 
            #5  \VvvvvvV/ 
            #6   `¯---¯´  
            #7             
            ############################  1     2     3   4   5   6         7           8   9   A   B       C   D  #0
            cut "\\e[$OY;${SX}H$SKY"     '' $X1' '   ' ' ' ' ' ' ' '       ' '         ' ' ' ' ' ' ' '     ' '     #1
            cut "\\e[$[OY+1];${SX}H$CM1" '' $X2' '   ' ' '.' '-' '.' ${pumtop[AS]} $CM1'.' '-' '.' ' '     ' ' ' ' #2
            cut "\\e[$[OY+2];${SX}H$CM1" ' '   ' '   '/'    $EYE           ' '            $EYE $CM1'\\'    ' ' ' ' #3
            cut "\\e[$[OY+3];${SX}H$CM1" ' '   '❲'   ' '           ${mouthtop[AS]}                 ' ' $CM1'❳' ' ' #4
            cut "\\e[$[OY+4];${SX}H$CM1" ' '   ' '   '\\'          ${mouthlow[AS]}             $CM1'/'     ' ' ' ' #5
            cut "\\e[$[OY+5];${SX}H$CM1" '' $X3' '   ' ' '`' '¯' '-'       '-'         '-' '¯' '´' ' '     ' '     #6
            cut "\\e[$[OY+6];${SX}H$SKY" ''    '' $X4' ' ' ' ' ' ' '       ' '         ' ' ' ' ' ' ' '             #7
            ENM[i]="boss $OX $OY 6 14 $SC $SM $CS $CL $AS 6 $C1";;
        *covid-19)
            CM1=$SKY$BLD$ylw CM2=$BLD$RED EYE="$CM2( $CM2⁐ $CM2)"
            X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+1];$[OX+1]H" X3="\\e[$[OY+5];$[OX+1]H" X4="\\e[$[OY+6];$[OX+2]H"
            #0123456789ABCD
            #1             
            #2   . ___,   
            #3   /`   `\  
            #4 +|       |+
            #5  \       /  
            #6  *`-.,.-`+  
            #7             
            ############################  1     2     3   4   5   6         7           8   9   A   B       C   D  #0
            cut "\\e[$OY;${SX}H$SKY"     '' $X1' '   ' ' ' ' ' ' ' '       ' '         ' ' ' ' ' ' ' '     ' '     #1
            cut "\\e[$[OY+1];${SX}H$CM1" '' $X2' '   ' ' '.' '-' '.' ${pumtop[AS]} $CM1'.' '-' '.' ' '     ' ' ' ' #2
            cut "\\e[$[OY+2];${SX}H$CM1" ' '   ' '   '/'    $EYE           ' '            $EYE $CM1'\\'    ' ' ' ' #3
            cut "\\e[$[OY+3];${SX}H$CM1" ' '   '❲'   ' '           ${mouthtop[AS]}                 ' ' $CM1'❳' ' ' #4
            cut "\\e[$[OY+4];${SX}H$CM1" ' '   ' '   '\\'          ${mouthlow[AS]}             $CM1'/'     ' ' ' ' #5
            cut "\\e[$[OY+5];${SX}H$CM1" '' $X3' '   ' ' '`' '¯' '-'       '-'         '-' '¯' '´' ' '     ' '     #6
            cut "\\e[$[OY+6];${SX}H$SKY" ''    '' $X4' ' ' ' ' ' ' '       ' '         ' ' ' ' ' ' ' '             #7
            ENM[i]="boss $OX $OY 6 14 $SC $SM $CS $CL $AS 6 $C1";;
        *)
            CM1=$SKY$DIM$BLK CM2=$BLD$BLK
            X1="\\e[$OY;$[OX+4]H" X2="\\e[$[OY+1];$[OX+2]H" X3="\\e[$[OY+2];$[OX+1]H" X4="\\e[$[OY+6];$[OX+1]H"
            #0123456789ABCD
            #1             
            #2     ___          
            #3   _/   \_   
            #4  /       \  
            #5 (         ) 
            #6  `¯¯---¯¯´  
            #7             
            ############################   1     2     3   4     5    6   7   8       9    A   B         C   D  #0
            cut "\\e[$OY;${SX}H$SKY"      ''    ''    ''  '' $X1' '  ' ' ' ' ' '     ' '                        #1
            cut "\\e[$[OY+1];${SX}H$CM2"  ''    '' $X2' ' ' '   ' '  '_' '_' '_'     ' '  ' ' ' '               #2
            cut "\\e[$[OY+2];${SX}H$CM1"  '' $X3' '   ' ' '_'   '/' ${small[AS]} $CM2'\\' '_' ' '       ' '     #3
            cut "\\e[$[OY+3];${SX}H$CM1"  ' '   ' '   '/'            ${big1[AS]}          $CM2'\\'      ' ' ' ' #4
            cut "\\e[$[OY+4];${SX}H$CM1"  ' '   '('   ' '            ${big2[AS]}              ' ' "$CM2"')' ' ' #5
            cut "\\e[$[OY+5];${SX}H$CM1"  ' '   ' '   '`' '¯'   '¯'  '-' '-' '-'     '¯'  '¯' '´'       ' ' ' ' #6
            cut "\\e[$[OY+6];${SX}H$SKY"  '' $X4' '   ' ' ' '   ' '  ' ' ' ' ' '     ' '  ' ' ' '       ' '     #7
            ENM[i]="boss $OX $OY 6 14 $SC $SM $CS $CL $AS $AL $C1";;
    esac
}
#------------------------{ Bonuses }------------------------------------------------------------------------------------
sprite_ammo () {
    case "$day$month$virus" in
        *covid-19)
            mov - && ENM[i]="ammo $OX $OY 3 6 $SC $SM $CS $CL $AS 3 $i" || { unset ENM[i]; return; }
            X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H" CM1=$SKY$BLD$red CM2=$SKY$BLU 
            #0123456
            #1 _ _  
            #2(_|_) 
            #3(_|_) 
            ############################  1     2   3       4          5  6    #0
            cut "\\e[$OY;${SX}H$CM1"     '' $X1'_' ' ' $CM2'_' "$CM2"' '       #1
            cut "\\e[$[OY+1];${SX}H$CM1" '('   '_' '|' $CM2'_' "$CM2"')' ' '   #2
            cut "\\e[$[OY+2];${SX}H$CM1" '('   '_' '|' $CM2'_' "$CM2"')' ' ';; #3
        *)
            mov - && ENM[i]="ammo $OX $OY 3 4 $SC $SM $CS $CL $AS 3 $i" || { unset ENM[i]; return; }
            CM1=$SKY$BLD$red CM2=$SKY$GRN
            #01234
            #1-=> 
            #2-=> 
            #3-=> 
            ############################  1   2       3   4    #0
            cut "\\e[$OY;${SX}H$CM1"     '-' '=' $CM2'>' ' '   #1
            cut "\\e[$[OY+1];${SX}H$CM1" '-' '=' $CM2'>' ' '   #2
            cut "\\e[$[OY+2];${SX}H$CM1" '-' '=' $CM2'>' ' ';; #3
    esac
}
sprite_life () {
    mov - && ENM[i]="life $OX $OY 3 4 $SC $SM $CS $CL $AS 3 $i" || { unset ENM[i]; return; }
    CM1=$SKY$RED X1="\\e[$[OY+2];$[OX+1]H"
    #01234
    #1/V\ 
    #2\ / 
    #3 V  
    ############################  1     2   3    4  #0
    cut "\\e[$OY;${SX}H$CM1"     '/'   'V' '\\' ' ' #1
    cut "\\e[$[OY+1];${SX}H$CM1" '\\'  ' ' '/'  ' ' #2
    cut "\\e[$[OY+2];${SX}H$CM1" '' $X1'V' ' '      #3
}
sprite_gunup () {
    mov - && ENM[i]="gunup $OX $OY 3 4 $SC $SM $CS $CL $AS 3 $i" || { unset ENM[i]; return; }
    CM1=$SKY$BLK CM2=$SKY$blk CM3=$SKY$UND$blk
    case ${G} in
        1) #01234
           #1‖—— 
           #2‖   
           #3‖—— 
           ############################  1       2       3   4    #0
           cut "\\e[$OY;${SX}H$CM1"     '‖' $CM2'—' $CM2'—' ' '   #1
           cut "\\e[$[OY+1];${SX}H$CM1" '‖' $SKY' '               #2
           cut "\\e[$[OY+2];${SX}H$CM1" '‖' $CM2'—' $CM2'—' ' ';; #3
        2) #01234
           #1‖—— 
           #2‖—— 
           #3‖—— 
           ############################  1       2       3   4    #0
           cut "\\e[$OY;${SX}H$CM1"     '‖' $CM2'—' $CM2'—' ' '   #1
           cut "\\e[$[OY+1];${SX}H$CM1" '‖' $CM2'—' $CM2'—' ' '   #2
           cut "\\e[$[OY+2];${SX}H$CM1" '‖' $CM2'—' $CM2'—' ' ';; #3
        3) #01234
           #1‖== 
           #2‖   
           #3‖== 
           ############################  1       2       3       4    #0
           cut "\\e[$OY;${SX}H$CM1"     '‖' $CM3'‾' $CM3'‾' $SKY' '   #1
           cut "\\e[$[OY+1];${SX}H$CM1" '‖' $SKY' '                   #2
           cut "\\e[$[OY+2];${SX}H$CM1" '‖' $CM3'‾' $CM3'‾' $SKY' ';; #3
        *) #01234
           #1‖== 
           #2‖—— 
           #3‖== 
           ############################  1       2       3       4    #0
           cut "\\e[$OY;${SX}H$CM1"     '‖' $CM3'‾' $CM3'‾' $SKY' '   #1
           cut "\\e[$[OY+1];${SX}H$CM1" '‖' $CM2'—' $CM2'—'     ' '   #2
           cut "\\e[$[OY+2];${SX}H$CM1" '‖' $CM3'‾' $CM3'‾' $SKY' ';; #3
    esac
}
#------------------------{ Ad plane }-----------------------------------------------------------------------------------
flame1=("$red-"       "$ylw~"       "$red- $RED~" "$ylw-")
flame2=("$ylw-"       "$red- $RED~" "$red~"       "$YLW~")
flame3=("$red- $RED~" "$red~"       "$YLW~"       "$ylw-")
for ((i=0; i<${#ad}; i++)); do ad_new+="$BLD$red${ad:$i:1} "; done
new_ad=( ${ad_new//  /_Z_ } ) line=( ${new_ad[@]//*/$blk-} ) width=$((19+${#new_ad[@]}))
sprite_msngr () {
    mov - && BP2[i]="msngr $OX $OY 4 $width $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
    CM1=$SKY$BLD$blk CM2=$SKY$DIM$blk CM3=$SKY$blk
    X1="\\e[$OY;$[OX+7]H"     X2="\\e[$[OY+1];$[OX+1]H" X3="\\e[$[OY+1];$[OX+12]H"
    X4="\\e[$[OY+3];$[OX+4]H" X5="\\e[$[OY+3];$[OX+12]H"
    #0123456789ABCD...
    #1       __    
    #2 _____/_/   +------------------+~
    #3(°_\ |_)---<| Die alien scum! -~
    #4    \|      +-----------------~
    ############################  1       2   3       4      5        6       7       8   9   A   B   C     D   E   F  ...                                    #0
    cut "\\e[$OY;${SX}H$CM1"     ''      ''  ''      ''     ''       ''      ''   $X1'_' '_' ' '                                                              #1
    cut "\\e[$[OY+1];${SX}H$CM2" ''   $X2'_' '_'     '_'    '_'      '_'     '/'     '_' '/' ' ' ''  '' $X3'+' '-' '-' ${line[@]} ${flame1[AS]}   ' ' ' '     #2
    cut "\\e[$[OY+2];${SX}H$CM1" '(' $UND'°' ' ' $CM2'\\'   ' '  $CM3'|' $UND' ' $CM3')' '-' '-' '-' '<'   '|' ' ' ${new_ad[@]} ' ' $SKY${flame2[AS]} ' ' ' ' #3
    cut "\\e[$[OY+3];${SX}H$CM2" ''      ''  ''       '' $X4'\\' $CM3'|'     ' '     ''  ''  ''  ''  '' $X5'+' ${line[@]} ${flame3[AS]}           ' ' ' '     #4
}
#------------------------{ Clouds }-------------------------------------------------------------------------------------
case $month in
    0[1-4]|12) C1C=$SKY$DIM$CYN;; # winter & early spring
    0[5-8]   ) C1C=$SKY$DIM$WHT;; # late spring & summer
    09|1[0-1]) C1C=$SKY$blk    ;; # autumn
esac
sprite_cloud1 () {
    mov - && BP1[i]="cloud1 $OX $OY 3 6 $SC $SM $CS $CL $AS $AL" || { unset BP1[i]; return; }
    X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
    #01234567
    #1 ,-+.  
    #2(    ) 
    #3 `+-´  
    #############################  1     2   3   4   5   6   7  #0
    cut "\\e[$OY;${SX}H$C1C"      '' $X1',' '-' '+' '.' ' '     #1
    cut "\\e[$[$OY+1];${SX}H$C1C" '('   ' ' ' ' ' ' ' ' ')' ' ' #2
    cut "\\e[$[$OY+2];${SX}H$C1C" '' $X2'`' '+' '-' '´' ' '     #3
}

case $month in
    0[1-4]|12) C2C=$SKY$CYN;; # winter & early spring
    0[5-8]   ) C2C=$SKY$WHT;; # late spring & summer
    09|1[0-1]) C2C=$SKY$BLK;; # autumn
esac
sprite_cloud2 () {
    mov - && BP2[i]="cloud2 $OX $OY 3 8 $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
    X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
    #0123456789
    #1 ,-._..  
    #2(      ) 
    #3 `-...´  
    #############################  1     2   3   4   5   6   7   8   9  #0
    cut "\\e[$OY;${SX}H$C2C"      '' $X1',' '-' '.' '_' '.' '.' ' '     #1
    cut "\\e[$[$OY+1];${SX}H$C2C" '('   ' ' ' ' ' ' ' ' ' ' ' ' ')' ' ' #2
    cut "\\e[$[$OY+2];${SX}H$C2C" '' $X2'`' '-' '.' '.' '.' '´' ' '     #3
}

case $month in
    0[1-4]|12) C3C=$SKY$BLD$CYN;; # winter & early spring
    0[5-8]   ) C3C=$SKY$BLD$WHT;; # late spring & summer
    09|1[0-1]) C3C=$SKY$DIM$BLK;; # autumn
esac
sprite_cloud3 () {
    mov - && BP3[i]="cloud3 $OX $OY 3 11 $SC $SM $CS $CL $AS $AL" || { unset BP3[i]; return; }
    X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H"
    #0123456789ABC
    #1 ,+¯`.-¯`.  
    #2(         ) 
    #3 `--.,,.-´  
    #############################  1     2   3   4   5   6   7   8   9   A   B   C  #0
    cut "\\e[$OY;${SX}H$C3C"      '' $X1',' '+' '¯' '`' '.' '-' '¯' '`' '.' ' '     #1
    cut "\\e[$[$OY+1];${SX}H$C3C" '('   ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ')' ' ' #2
    cut "\\e[$[$OY+2];${SX}H$C3C" '' $X2'`' '-' '-' '.' ',' ',' '.' '-' '´' ' '     #3
}

#------------------------{ Trees }--------------------------------------------------------------------------------------
case $month in
    0[1-4]|12) T1C=$SKY$DIM$WHT tree1H=3;; # winter & early spring
    0[5-8]   ) T1C=$SKY$DIM$GRN tree1H=4;; # late spring & summer
    09|1[0-1]) T1C=$SKY$DIM$YLW tree1H=4;; # autumn
esac
sprite_tree1 () {
    case $month in
        0[1-4]|12)
            mov - && BP1[i]="tree1 $OX $OY 3 2 $SC $SM $CS $CL $AS $AL" || { unset BP1[i]; return; }
            X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+2];$[OX+1]H" CM1="$DIM$blk"
            #01234
            #1 |/ 
            #2\|  
            #3 |  
            #############################  1        2   3   4  #0
            cut "\\e[$OY;${SX}H$T1C"      ''    $X1'|' '/' ' ' #1
            cut "\\e[$[$OY+1];${SX}H$T1C" '\\' $CM1'|' ' '     #2
            cut "\\e[$[$OY+2];${SX}H$CM1" ''    $X2'|' ' ';;   #3
        *)
            mov - && BP1[i]="tree1 $OX $OY 4 2 $SC $SM $CS $CL $AS $AL" || { unset BP1[i]; return; }
            CM1="$DIM$blk" X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+3];$[OX+1]H$CM1" 
            #01234
            #1 _  
            #2/ \ 
            #3\|/ 
            #4 |  
            #############################  1        2       3    4  #0
            cut "\\e[$OY;${SX}H$T1C"      ''    $X1'_'     ' '      #1
            cut "\\e[$[$OY+1];${SX}H$T1C" '/'      ' '     '\\' ' ' #2
            cut "\\e[$[$OY+2];${SX}H$T1C" '\\' $CM1'|' $T1C'/'  ' ' #3
            cut "\\e[$[$OY+3];${SX}H$T1C" ''    $X2'|'     ' ';;    #4
    esac
}

case $month in
    0[1-4]|12) T2C=$SKY$WHT tree2H=5;; # winter & early spring
    0[5-8]   ) T2C=$SKY$GRN tree2H=6;; # late spring & summer
    09|1[0-1]) T2C=$SKY$YLW tree2H=6;; # autumn
esac
sprite_tree2 () {
    case $month in
        0[1-4]|12)
            mov - && BP2[i]="tree2 $OX $OY 5 5 $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
            X1="\\e[$OY;$[OX+3]H" X2="\\e[$[OY+2];$[OX+1]H" X3="\\e[$[OY+3];$[OX+2]H" X4="\\e[$[OY+4];$[OX+2]H"
            #0123456
            #1   |_ 
            #2\||/  
            #3 \║|_ 
            #4  ║/  
            #5  ║   
            #############################  1     2        3       4   5   6  #0
            cut "\\e[$OY;${SX}H$T2C"      ''    ''       ''   $X1'|' '_' ' ' #1
            cut "\\e[$[$OY+1];${SX}H$T2C" '\\'  '|'  $blk'|'     '/' ' '     #2
            cut "\\e[$[$OY+2];${SX}H$blk" '' $X2'\\'     '║' $T2C'|' '_' ' ' #3
            cut "\\e[$[$OY+3];${SX}H$blk" ''    ''    $X3'║'     '/' ' '     #4
            cut "\\e[$[$OY+4];${SX}H$blk" ''    ''    $X4'║'     ' ';;       #5
        *)
            mov - && BP2[i]="tree2 $OX $OY 6 5 $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
            X1="\\e[$OY;$[OX+1]H" X2="\\e[$[OY+3];$[OX+1]H" X3="\\e[$[OY+4];$[OX+2]H" X4="\\e[$[OY+5];$[OX+2]H"
            #0123456
            #1 _._  
            #2/   \ 
            #3\ | / 
            #4 \║/\ 
            #5  ║_/ 
            #6  ║   
            #############################  1     2        3       4       5    6  #0
            cut "\\e[$OY;${SX}H$T2C"      '' $X1'_'      '.'     '_'     ' '      #1
            cut "\\e[$[$OY+1];${SX}H$T2C" '/'   ' '      ' '     ' '     '\\' ' ' #2
            cut "\\e[$[$OY+2];${SX}H$T2C" '\\'  ' '  $blk'|'     ' ' $T2C'/'  ' ' #3
            cut "\\e[$[$OY+3];${SX}H$T2C" '' $X2'\\' $blk'║' $T2C'/'     '\\' ' ' #4
            cut "\\e[$[$OY+4];${SX}H$blk" ''    ''    $X3'║' $T2C'_'     '/'  ' ' #5
            cut "\\e[$[$OY+5];${SX}H$blk" ''    ''    $X4'║'     ' ';;            #6
    esac
}

case $month in
    0[1-4]|12) T3C=$SKY$BLD$cyn tree3H=8;; # winter & early spring
    0[5-8]   ) T3C=$SKY$GRN     tree3H=9;; # late spring & summer
    09|1[0-1]) T3C=$SKY$DIM$red tree3H=9;; # autumn
esac
sprite_tree3 () {
    case "$day$month" in
        2[1-9]12|3[0-1]12|0[1-9]01|1001)
            mov - && BP3[i]="tree3 $OX $OY 8 12 $SC $SM $CS $CL $AS $AL" || { unset BP3[i]; return; }
            X1="\\e[$OY;$[OX+6]H"     X2="\\e[$[OY+1];$[OX+4]H"     X3="\\e[$[OY+2];$[OX+4]H" X4="\\e[$[OY+3];$[OX+4]H$RED"
            X5="\\e[$[OY+4];$[OX+2]H" X6="\\e[$[OY+5];$[OX+2]H$red" X7="\\e[$[OY+7];$[OX+6]H"
            #0123456789ABCD
            #1      ★      
            #2    _❅|●     
            #3    -/○\❄-   
            #4    ●/|\\○   
            #5  _/❄/●\❅\   
            #6  ○///|\❄\●  
            #7_/❅/●/|○\❅\- 
            #8      ║      
            #############################  1   2       3       4       5       6       7       8       9         A        B    C   D  #0
            cut "\\e[$OY;${SX}H$RED"      ''  ''      ''      ''      ''      ''   $X1'★'     ' '                                     #1
            cut "\\e[$[$OY+1];${SX}H$GRN" ''  ''      ''      ''   $X2'_' $cyn'❅' $GRN'|' $BLU'●'      ' '                            #2
            cut "\\e[$[$OY+2];${SX}H$GRN" ''  ''      ''      ''   $X3'-'     '/' $YLW'○' $GRN'\\' $CYN'❄'  $GRN'-'      ' '          #3
            cut "\\e[$[$OY+3];${SX}H$GRN" ''  ''      ''      ''   $X4'●' $GRN'/'     '|'     '\\'     '\\' $ylw'○'      ' '          #4
            cut "\\e[$[$OY+4];${SX}H$GRN" ''  ''   $X5'_'     '/' $cyn'❄' $GRN'/' $blu'●' $GRN'\\' $cyn'❅'  $GRN'\\'     ' '          #5
            cut "\\e[$[$OY+5];${SX}H$GRN" ''  ''   $X6'○' $GRN'/'     '/'     '/'     '|'     '\\' $CYN'❄'  $GRN'\\' $RED'●'  ' '     #6
            cut "\\e[$[$OY+6];${SX}H$GRN" '_' '/' $cyn'❅' $GRN'/' $YLW'●' $GRN'/'     '|' $RED'○'  $GRN'\\' $cyn'❅'  $GRN'\\' '-' ' ' #7
            cut "\\e[$[$OY+7];${SX}H$BLK" ''  ''      ''      ''      ''      ''   $X7'║'     ' ';;                                   #8
        0[1-4]|12)
            mov - && BP3[i]="tree3 $OX $OY 8 9 $SC $SM $CS $CL $AS $AL" || { unset BP3[i]; return; }
            X1="\\e[$OY;$[OX+2]H"     X2="\\e[$[OY+1];$[OX+3]H" X3="\\e[$[OY+3];$[OX+1]H" X4="\\e[$[OY+4];$[OX+3]H"
            X5="\\e[$[OY+5];$[OX+4]H" X6="\\e[$[OY+6];$[OX+4]H" X7="\\e[$[OY+7];$[OX+4]H"
            #0123456789A
            #1  \|      
            #2   \| |_  
            #3_\_ ║/    
            #4 /\ ║ \/_ 
            #5   \║ /   
            #6    ║/    
            #7    ║     
            #8    ║     
            #############################  1     2     3     4       5       6       7    8   9   A  #0
            cut "\\e[$OY;${SX}H$T3C"      ''    '' $X1'\\'  '|'     ' '                              #1
            cut "\\e[$[$OY+1];${SX}H$BLK" ''    ''    '' $X2'\\'    '|'     ' ' $T3C'|'  '_' ' '     #2
            cut "\\e[$[$OY+2];${SX}H$T3C" '_'   '\\'  '_'   ' ' $BLK'║'     '/'     ' '              #3
            cut "\\e[$[$OY+3];${SX}H$T3C" '' $X3'/'   '\\'  ' ' $BLK'║' $T3C' '     '\\' '/' '_' ' ' #4
            cut "\\e[$[$OY+4];${SX}H$BLK" ''    ''    '' $X4'\\'    '║'     ' '     '/'  ' '         #5
            cut "\\e[$[$OY+5];${SX}H$BLK" ''    ''    ''    ''   $X5'║'     '/'     ' '              #6
            cut "\\e[$[$OY+6];${SX}H$BLK" ''    ''    ''    ''   $X6'║'     ' '                      #7
            cut "\\e[$[$OY+7];${SX}H$BLK" ''    ''    ''    ''   $X7'║'     ' ';;                    #8
        *)
            mov - && BP3[i]="tree3 $OX $OY 9 9 $SC $SM $CS $CL $AS $AL" || { unset B3[i]; return; }
            X1="\\e[$OY;$[OX+3]H"     X2="\\e[$[OY+1];$[OX+2]H" X3="\\e[$[OY+2];$[OX+1]H" X4="\\e[$[OY+5];$[OX+3]H"
            X5="\\e[$[OY+6];$[OX+4]H" X6="\\e[$[OY+7];$[OX+4]H" X7="\\e[$[OY+8];$[OX+4]H"
            #0123456789A
            #1   _._    
            #2  /   \   
            #3 _\ | /   
            #4/  \║/__  
            #5\_\/║/  \ 
            #6   \║|/_/ 
            #7    ║/    
            #8    ║     
            #9    ║     
            #############################  1     2       3        4        5       6       7       8   9    A  #0
            cut "\\e[$OY;${SX}H$T3C"      ''    ''      ''    $X1'_'      '.'     '_'     ' '                  #1
            cut "\\e[$[$OY+1];${SX}H$T3C" ''    ''   $X2'/'      ' '      ' '     ' '     '\\'    ' '          #2
            cut "\\e[$[$OY+2];${SX}H$T3C" '' $X3'_'     '\\'     ' '  $BLK'|'     ' ' $T3C'/'     ' '          #3
            cut "\\e[$[$OY+3];${SX}H$T3C" '/'   ' '     ' '      '\\' $BLK'║' $T3C'/'     '_'     '_' ' '      #4
            cut "\\e[$[$OY+4];${SX}H$T3C" '\\'  '_' $BLK'\\' $T3C'/'  $BLK'║' $T3C'/'     ' '     ' ' '\\' ' ' #5
            cut "\\e[$[$OY+5];${SX}H$BLK" ' '   ' '     ' '   $X4'\\'     '║' $T3C'|' $BLK'/' $T3C'_' '/'  ' ' #6
            cut "\\e[$[$OY+6];${SX}H$BLK" ''    ''      ''       ''    $X5'║'     '/'     ' '                  #7
            cut "\\e[$[$OY+7];${SX}H$BLK" ''    ''      ''       ''    $X6'║'     ' '                          #8
            cut "\\e[$[$OY+8];${SX}H$BLK" ''    ''      ''       ''    $X7'║'     ' ';;                        #9
    esac
}
#------------------------{ Bird }---------------------------------------------------------------------------------------
# ⌄ _ 
#     ^
sprite_bird () {
    mov - && BP1[i]="bird $OX $OY 2 2 $SC $SM $CS $CL $AS $AL" || { unset BP1[i]; return; }
    case $AS in
          0) cut "\\e[$OY;${SX}H$SKY$blk"      '⌄' ' '
             cut "\\e[$[$OY+1];${SX}H$SKY"     ' ' ' ';;
          1) cut "\\e[$OY;${SX}H$SKY$blk"      '_' ' '
             cut "\\e[$[$OY+1];${SX}H$SKY"     ' ' ' ';;
          2) cut "\\e[$OY;${SX}H$SKY"          ' ' ' '
             cut "\\e[$[$OY+1];${SX}H$SKY$blk" '^' ' ';;
    esac
}
#------------------------{ House }--------------------------------------------------------------------------------------
# ╌ ╍ ─ ━ ┄ ┅ ┈ ┉ ═ ╴╶ ╸╺ ╼ ╾ ╲  ╵ ╷ ╹ ╻ ╽ ╿ │ ┃ ╎ ╏ ┆ ┇ ┊ ┋ ╰ ╱ ┌ ┍ ┎ ┏ ┐ ┑ ┒ ┓ └ ┕ ┖ ┗ ┘ ┙ ┚ ┛ ├ ┝ ┞ ┟ ┠ ┡ ┢ ┣ ┤ ┥ ┦
# ┧ ┨ ┩ ┪ ┫ ┬ ┭ ┮ ┯ ┱ ┲ ┳ ┴ ┵ ┶ ┷ ┸ ┹ ┺ ┻ ┼ ┽ ┾ ┿ ╀ ╁ ╂ ╃ ╄ ╅ ╆ ╇ ╈ ╉ ╊ ╋ ║ ╒ ╓ ╔ ╕ ╖ ╗ ╘ ╙ ╚ ╛ ╜ ╝  ╟ ╠ ╡ ╢ ╣ ╤ ╥ ╦ ╧
sprite_house1 () { #╨ ╩ ╪ ╫ ╬ ╭ ╮ ╯ ▀ ▁ ▂ ▃ ▄ ▅ ▆ ▇ █ ▉ ▊ ▋ ▌ ▍ ▎ ▏▐ ░ ▒ ▓ ▔ ▕ ▖ ▗ ▘ ▙ ▚ ▛ ▜ ▝ ▞ ▟
    mov - && BP1[i]="house1 $OX $OY 2 6 $SC $SM $CS $CL $AS $AL" || { unset BP1[i]; return; }
    CM1=$SKY$DIM$GRN CM2=$SKY$blk
    #0123456
    #1▁▂▃▂▁ 
    #2│▘▝▝| 
    ############################  1   2   3   4   5   6  #0
    cut "\\e[$OY;${SX}H$CM1"     '▁' '▂' '▃' '▂' '▁' ' ' #1
    cut "\\e[$[OY+1];${SX}H$CM2" '│' '▘' '▝' '▝' '|' ' ' #2
}
sprite_house2 () {
    mov - && BP2[i]="house2 $OX $OY 9 30 $SC $SM $CS $CL $AS $AL" || { unset BP2[i]; return; }
    CM1="$SKY$BLU" CM2=$SKY$BLD$YLW CM3=$SKY$YLW CM4=$SKY$ylw CM5=$SKY$blk
    X1="\\e[$OY;$[OX+9]H"     X2="\\e[$[OY+1];$[OX+9]H" X3="\\e[$[OY+2];$[OX+8]H" X4="\\e[$[OY+3];$[OX+8]H"
    X5="\\e[$[OY+4];$[OX+7]H" X6="\\e[$[OY+5];$[OX+7]H" X7="\\e[$[OY+6];$[OX+6]H" X8="\\e[$[OY+7];$[OX+6]H"
    #0123456789ABCDEFJHIJKLMNOPQRSTU
    #1         ╂                    
    #2         ╧                    
    #3        ╱ ╲                   
    #4        |▐|                   
    #5       ┮┷━┷┭                  
    #6       │ █ |                  
    #7      ┮┷━━━┷┭                 
    #8      │ ▛▔▜ │▄▄▄▄▂▁           
    #9▂ ╬ ▃ ┃ ▌▒▐ ┃ ▘▗▘┿┃▗ ╂ ╪ ▄  ▖ 
    ################################  1   2   3   4   5   6     7     8     9     A   B   C   D       E       F       J       H       I       J   K   L   M   N   O   P   Q   R   S   T   U  #0
    cut "\\e[$OY;${SX}H$CM2"         ''  ''  ''  ''  ''  ''    ''    ''    '' $X1'╂' ' '                                                                                                     #1
    cut "\\e[$[OY+1];${SX}H$CM3"     ''  ''  ''  ''  ''  ''    ''    ''    '' $X2'╧' ' '                                                                                                     #2
    cut "\\e[$[OY+2];${SX}H$CM4"     ''  ''  ''  ''  ''  ''    ''    '' $X3'╱'   ' ' '╲' ' '                                                                                                 #3
    cut "\\e[$[OY+3];${SX}H$CM5"     ''  ''  ''  ''  ''  ''    ''    '' $X4'|'   '▐' '|' ' '                                                                                                 #4
    cut "\\e[$[OY+4];${SX}H$CM1"     ''  ''  ''  ''  ''  ''    '' $X5'┮'   '┷'   '━' '┷' '┭' ' '                                                                                             #5
    cut "\\e[$[OY+5];${SX}H$CM5"     ''  ''  ''  ''  ''  ''    '' $X6'│'   ' '   '█' ' ' '│' ' '                                                                                             #6
    cut "\\e[$[OY+6];${SX}H$CM1"     ''  ''  ''  ''  ''  '' $X7'┮'   '┷'   '━'   '━' '━' '┷' '┭'     ' '                                                                                     #7
    cut "\\e[$[OY+7];${SX}H$CM5"     ''  ''  ''  ''  ''  '' $X8'│'   ' '   '▛'   '▔' '▜' ' ' '│' $CM1'▄' $CM1'▄' $CM1'▄' $CM1'▄' $CM6'▂' $CM6'▁' ' '                                         #8
    cut "\\e[$[OY+8];${SX}H$CM5"     '▂' ' ' '╬' ' ' '▃' ' '   '┃'   ' '   '▌'   '▒' '▐' ' ' '┃'     ' '     '▘'     '▗'     '▘'     '┿'     '┃' '▗' ' ' '╂' ' ' '╪' ' ' '▄' ' ' ' ' '▖' ' ' #9
}
sprite_house3 () {
    mov - && BP3[i]="house3 $OX $OY 4 17 $SC $SM $CS $CL $AS $AL" || { unset BP3[i]; return; }
    CM1=$SKY$DIM$MGN CM2=$SKY$blk CM3=$SKY$DIM$CYN
    X1="\\e[$OY;$[OX+5]H" X2="\\e[$[OY+1];$[OX+2]H" X3="\\e[$[OY+2];$[OX+2]H"
    #0123456789ABCDEFJHI
    #1     ▖            
    #2  ▂▄▆██▆▄▂        
    #3  ┃╒╕╒╕╒╕┃ ┮━┭    
    #4╠╬┃┵┘┵┶└┶┃╬╣▓╠╬╣▖ 
    ############################  1   2       3       4       5       6       7       8       9   A       B   C       D       E   F   J       H   I  #0
    cut "\\e[$OY;${SX}H$CM2"     ''  ''      ''      ''      ''   $X1'▖'     ' '                                                                     #1
    cut "\\e[$[OY+1];${SX}H$CM1" ''  ''   $X2'▂'     '▄'     '▆'     '█'     '█'     '▆'     '▄' '▂'     ' '                                         #2
    cut "\\e[$[OY+2];${SX}H$CM2" ''  ''   $X3'┃'     '╒'     '╕'     '╒'     '╕'     '╒'     '╕' '┃'     ' ' '┮'     '━'     '┭' ' '                 #3
    cut "\\e[$[OY+3];${SX}H$CM3" '╠' '╬' $CM2'┃' $CM2'┵' $CM2'┘' $CM2'┵' $CM2'┶' $CM2'└' $CM2'┶' '┃' $CM3'╬' '╣' $CM2'▓' $CM3'╠' '╬' '╣' $CM2'▖' ' ' #4
}
#------------------------{ BOOM }---------------------------------------------------------------------------------------
sprite_boom () {
    BX=$OX BY=$OY
    [[ $AS -ge $AL ]] && { unset BP3[i]; return; }
    case $AS in
          0) cut "\e[$BY;$[BX+3]H$YLW"             '_'      #     _
             cut "\e[$[BY+1];$[BX+2]H$YLW"        '(_)';;   #    (_)
          1) cut "\e[$BY;$[BX+2]H$RED"            '.-.'     #    .-.
             cut "\e[$[BY+1];$[BX+1]H$RED"       '(   )'    #   (   )
             cut "\e[$[BY+2];$[BX+1]H$RED"        '`-´';;   #    `-´
          2) cut "\e[$[BY-1];$[BX+3]H$red"         '_'      #     _
             cut "\e[$BY;$[BX+1]H$red"           '-   +'    #   -   +
             cut "\e[$[BY+1];${BX}H$red"        '(     )'   #  (     )
             cut "\e[$[BY+2];$[BX+1]H$red"       '+ _ -';;  #   + _ -
          3) cut "\e[$[BY-1];$[BX+2]H$DIM$RED"    '- -'     #    - -
             cut "\e[$BY;${BX}H$DIM$RED"        '´     `'   #  ´     `
             cut "\e[$[BY+1];$[BX-1]H$DIM$RED" "'       '"  # '       '
             cut "\e[$[BY+2];${BX}H$DIM$RED"    '`  _  ´';; #  `  _  ´
          4) cut "\e[$[BY-1];$[BX+2]H$SKY"        '   '     #  eraser
             cut "\e[$BY;${BX}H$SKY"            '       '   #
             cut "\e[$[BY+1];$[BX-1]H$SKY"     '         '  #
             cut "\e[$[BY+2];${BX}H$SKY"        '       ';; #
    esac
    mov -; BP3[i]="boom $BX $BY 0 0 $SC $SM $CS $CL $AS $AL"
}
#------------------------{ Sun }----------------------------------------------------------------------------------------
sprite_Sun () {
    mov -; BP1[i]="Sun $Sunsendx 1 9 18 $SC 7 $CS $CL $AS $AL"
    case $AS in
          0) cut "\e[1;${Sunsendx}H$SKY$YLW"     '       ___ |       '
             cut "\e[2;${Sunsendx}H$SKY$BLD$YLW" '---````    \       '
             cut "\e[3;${Sunsendx}H$SKY$YLW"     '           _`.     '
             cut "\e[4;${Sunsendx}H$SKY$BLD$YLW" '        ../   `..__'
             cut "\e[5;${Sunsendx}H$SKY$YLW"     '     ../        /  '
             cut "\e[6;${Sunsendx}H$SKY$YLW"     '    /          /   '
             cut "\e[7;${Sunsendx}H$SKY$BLD$YLW" '              /    '
             cut "\e[8;${Sunsendx}H$SKY$YLW"     '              /    '
             cut "\e[9;${Sunsendx}H$SKY$BLD$YLW" '             /     ';;
          1) cut "\e[1;${Sunsendx}H$SKY$YLW"     '_...---``  |       '
             cut "\e[2;${Sunsendx}H$SKY$BLD$YLW" '        _.-\       '
             cut "\e[3;${Sunsendx}H$SKY$YLW"     '   _.--`    `.     '
             cut "\e[4;${Sunsendx}H$SKY$YLW"     ' -`          ,`..__'
             cut "\e[5;${Sunsendx}H$SKY$BLD$YLW" '           ,`     |'
             cut "\e[6;${Sunsendx}H$SKY$YLW"     '         ,`       |'
             cut "\e[7;${Sunsendx}H$SKY$YLW"     '       _`        | '
             cut "\e[8;${Sunsendx}H$SKY$BLD$YLW" '                 | '
             cut "\e[9;${Sunsendx}H$SKY$YLW"     '                 | ';;
          2) cut "\e[1;${Sunsendx}H$SKY$BLD$YLW" '     _...--|       '
             cut "\e[2;${Sunsendx}H$SKY$BLD$YLW" '..--`      \       '
             cut "\e[3;${Sunsendx}H$SKY$BLD$YLW" '         .. `.     '
             cut "\e[4;${Sunsendx}H$SKY$YLW"     '     _.-`     `..__'
             cut "\e[5;${Sunsendx}H$SKY$BLD$YLW" '  ..`         .`   '
             cut "\e[6;${Sunsendx}H$SKY$BLD$YLW" '             /     '
             cut "\e[7;${Sunsendx}H$SKY$YLW"     '            /      '
             cut "\e[8;${Sunsendx}H$SKY$BLD$YLW" '          .`       '
             cut "\e[9;${Sunsendx}H$SKY$YLW"     '         `         ';;
    esac
}
