#!/usr/bin/env bash
# check bash version
case ${BASH_VERSINFO[@]::2} in [1-3]' '[0-9][0-9]|[1-3]' '[0-9]|'4 '[0-1])
    echo -e "\nYour BASH is too short!) 4.2+ required to run this game, your is - ${BASH_VERSINFO[@]}"
    exit 1;;
esac
. ~/SCR/color
#------------------------{ Start opt }------------------------{ description }-----------------{ def. values }-----------
     enumber=0                                        # current enemy counter                      (0)
       enmax=100                                      # max number of akiens                       (10)
        FPSL=100                                      # lower FPS initial value                    (100)
        FPSM=0                                        # maximum FPS initial value                  (0)
        FPSC=0                                        # FPS counter                                (0)
         SKY=$DEF
         spd=0.01                                     # game\read speed                            (0.0001)
         OBJ=()                                       # start obj array
           L=0                                        # sprites animation counter
[[ -e ~/.piuconf ]] && . ~/.piuconf
#------------------------{ Aliens }-------------------------------------------------------------------------------------
       # ___
       #( o )
       # `¯´
sprite_alien () {
       hight=3
       width=5; mov || return
       small=(               "$Y1$X1${RED}o    $Y1$X2${SKY}_   $Y1$X3${SKY}_"
                             "$Y1$X1${SKY}_    $Y1$X2${SKY}_   $Y1$X3${SKY}_"
                             "$Y1$X1${SKY}_    $Y1$X2${SKY}_   $Y1$X3${RED}o"
                             "$Y1$X1${SKY}_    $Y1$X2${RED}o   $Y1$X3${SKY}_" ); small=( "${small[L]//_/' '}" )
      sprite=( ''            "$Y0$X1${SKY}_"  "$Y0$X2${SKY}_" "$Y0$X3${SKY}_" "$Y0$X4$SKY "                   ); cut
      sprite=( "$Y1$X0$SKY("                  "${small[@]}"                   "$Y1$X4$SKY)" "$Y1$X5$SKY "     ); cut
      sprite=( ''            "$Y2$X1${SKY}\`" "$Y2$X2${SKY}¯" "$Y2$X3${SKY}´" "$Y2$X4$SKY "                   ); cut
}

#------------------------{ Functions }----------------------------------------------------------------------------------
get_dimensions () {
    size=( $(stty size) )
    endx=${size[1]}
    endy=${size[0]}
enmyendy=$[endy-7]
}

remove_obj () { unset  OBJ[$1]; OBJ=("${OBJ[@]}"); }
erase_obj  () { remove_obj $1 ; for (( k=0; k<$2; k++ )); do screen+="\e[$[OY+k];${OX}H$SKY         "; done; }

bye () { stty echo; printf "$CON$DEF"; exit $1; }
cut () { screen+="${sprite[@]:$OS:$OE}"; }
mov () {
    [[ $OX -le -$width ]] && { remove_obj $i; case $type in 'alien') ((enumber--));; esac; return 1; }
    Y0="\\e[$OY"    ; X0=";${OX}H"
    Y1="\\e[$[OY+1]"; X1=";$[OX+1]H"
    Y2="\\e[$[OY+2]"; X2=";$[OX+2]H"
    Y3="\\e[$[OY+3]"; X3=";$[OX+3]H"
    Y4="\\e[$[OY+4]"; X4=";$[OX+4]H"
    Y5="\\e[$[OY+5]"; X5=";$[OX+5]H"
    [[ $OX -le 0 ]] && ((OS++))    
    case $CS in
        0) ((OX--));          ((OE++)); OBJ[$i]="$OX $OY $OS $OE $type $DS $DS";;
        *) [[ $CS -gt 0 ]] && ((CS--)); OBJ[$i]="$OX $OY $OS $OE $type $CS $DS";;
    esac
}

fps_counter () {
    [[ $SECONDS -gt $sec ]] && {\
        FPS=$FPSC
        [[ $FPS -gt $FPSM ]] && FPSM=$FPS
        [[ $FPS -lt $FPSL ]] && FPSL=$FPS
        sec=$SECONDS
        FPSC=0
    } || ((FPSC++))
}

obj_loop () {
    for i in ${!OBJ[@]}; do
        OI=(${OBJ[$i]})
        OX=${OI[0]}; OY=${OI[1]}; OS=${OI[2]}; OE=${OI[3]}; type=${OI[4]}; CS=${OI[5]}; DS=${OI[6]}
        [[ $type ]] && sprite_$type
    done
}

game () {
    #======================================{ Main game loop single or server team mode }================================
    while true; do
        #-{ Empty screen, count fps, set timings}-----------------------------------------------------------------------
        [[ $M -ge 10 ]] && M=0 || ((M++)) # enemies born rate
        [[ $L -ge 3  ]] && L=0 || ((L++)) # sprites animation
        read -t$spd -s -n1 input &> /dev/null
        screen=; fps_counter
        #-{ Print FPS }-------------------------------------------------------------------------------------------------
        screen+="\e[$endy;2H${DEF}FPS: $RED$FPS ${DEF}max: $RED$FPSM ${DEF}low: $RED$FPSL "
        #-{ Restart aliens }--------------------------------------------------------------------------------------------
        [[ $enumber -lt $enmax && $M -eq 0 ]] && { ((enumber++)); OBJ+=("$endx $[RANDOM%$enmyendy+3] 0 0 alien 0 $[RANDOM%2]"); }
        #-{ Move\check\print objects }----------------------------------------------------------------------------------
        obj_loop
#        screen+="\e[1;1H${OBJ[@]}"
        printf "$screen"
    done
}

#--------------------------------------------------{ Initialisation }---------------------------------------------------
trap bye INT TERM SIGINT SIGTERM EXIT
get_dimensions; stty -echo; printf "$COF"; clear
sec=$SECONDS # set timer for FPS counter
OBJ=(); game

