#!/usr/bin/env bash
# check bash version
case ${BASH_VERSINFO[@]::2} in [1-3]' '[0-9][0-9]|[1-3]' '[0-9]|'4 '[0-1])
    echo -e "\nYour BASH is too short!) 4.2+ required to run this game, your is - ${BASH_VERSINFO[@]}"
    exit 1;;
esac
. ~/SCR/color
#------------------------{ Start opt }------------------------{ description }-----------------{ def. values }-----------
     enumber=0                                        # current enemy counter                      (0)
       enmax=100                                      # max number of akiens                       (10)
        FPSL=100                                      # lower FPS initial value                    (100)
        FPSM=0                                        # maximum FPS initial value                  (0)
        FPSC=0                                        # FPS counter                                (0)
         SKY=$DEF
         spd=0.01                                     # game\read speed                            (0.0001)
         OBJ=()                                       # start obj array
           L=0                                        # sprites animation counter
[[ -e ~/.piuconf ]] && . ~/.piuconf
#------------------------{ Aliens }-------------------------------------------------------------------------------------
       # ___
       #( o )
       # `¯´
sprite_alien () {
       hight=3
       width=5; mov || return
       small=(          "$Y1$X1${SKY}_    $Y1$X2${SKY}_   $Y1$X3${RED}o"
                        "$Y1$X1${SKY}_    $Y1$X2${RED}o   $Y1$X3${SKY}_"
                        "$Y1$X1${RED}o    $Y1$X2${SKY}_   $Y1$X3${SKY}_"
                        "$Y1$X1${SKY}_    $Y1$X2${SKY}_   $Y1$X3${SKY}_")

      cut ""            "$Y0$X1${SKY}_"  "$Y0$X2${SKY}_" "$Y0$X3${SKY}_" "$Y0$X4$SKY "
      cut "$Y1$X0$SKY("                   ${small[AC]//_/}               "$Y1$X4$SKY)" "$Y1$X5$SKY "
      cut ""            "$Y2$X1${SKY}\`" "$Y2$X2${SKY}¯" "$Y2$X3${SKY}´" "$Y2$X4$SKY "
}

#------------------------{ Functions }----------------------------------------------------------------------------------
get_dimensions () {
    size=( $(stty size) )
    endx=${size[1]}
    endy=${size[0]}
enmyendy=$[endy-7]
}

remove_obj () { unset  OBJ[$1]; OBJ=("${OBJ[@]}"); }
erase_obj  () { remove_obj $1 ; for (( k=0; k<$2; k++ )); do screen+="\e[$[OY+k];${OX}H$SKY         "; done; }

bye () { stty echo; printf "$CON$DEF"; exit $1; }
cut () { screen+="${@:$OS:$OE}"; }
mov () {
    [[ $OX -le -$width ]] && {
        [[ $type == 'alien' ]] && ((enumber--))
        remove_obj $i
        return 1
    }
    Y0="\\e[$OY"    ; X0=";${OX}H"
    Y1="\\e[$[OY+1]"; X1=";$[OX+1]H"
    Y2="\\e[$[OY+2]"; X2=";$[OX+2]H"
    Y3="\\e[$[OY+3]"; X3=";$[OX+3]H"
    Y4="\\e[$[OY+4]"; X4=";$[OX+4]H"
    Y5="\\e[$[OY+5]"; X5=";$[OX+5]H"
    case $CS in
        0) [[ $OX -le 0   ]] && ((OS++)); ((OX--)); ((OE++)); CS=$DS
           [[ $AC -ge $AD ]] &&   AC=0 || ((AC++));; # sprites animation;;
        *) [[ $CS -gt 0   ]] && ((CS--));;
    esac
    OBJ[$i]="$OX $OY $type $CS $DS $OE $OS $AC $AD"
}

fps_counter () {
    [[ $SECONDS -gt $sec ]] && {\
        FPS=$FPSC
        [[ $FPS -gt $FPSM ]] && FPSM=$FPS
        [[ $FPS -lt $FPSL ]] && FPSL=$FPS
        sec=$SECONDS
        FPSC=0
    } || ((FPSC++))
}

obj_loop () {
    for i in ${!OBJ[@]}; do
        OI=(${OBJ[$i]})
        OX=${OI[0]}; OY=${OI[1]}; type=${OI[2]}; CS=${OI[3]}; DS=${OI[4]}
        OE=${OI[5]}; OS=${OI[6]}; AC=${OI[7]};   AD=${OI[8]}
        [[ $type ]] && sprite_$type
    done
}

game () {
    #======================================{ Main game loop single or server team mode }================================
    while true; do
        #-{ Empty screen, count fps, set timings}-----------------------------------------------------------------------
        [[ $M -ge 10 ]] && M=0 || ((M++)) # enemies born rate
        read -t$spd -s -n1 input &> /dev/null
        screen=; fps_counter
        #-{ Print FPS }-------------------------------------------------------------------------------------------------
        screen+="\e[$endy;2H${DEF}FPS: $RED$FPS ${DEF}max: $RED$FPSM ${DEF}low: $RED$FPSL "
        #-{ Restart aliens }--------------------------------------------------------------------------------------------
        [[ $enumber -lt $enmax && $M -eq 0 ]] && {
            OBJ+=("$[endx-1] $[RANDOM%$enmyendy+3] alien 0 $[RANDOM%2] 1 1 $[RANDOM%3] 3")
            ((enumber++))
        }
        #-{ Move\check\print objects }----------------------------------------------------------------------------------
        obj_loop; printf "$screen"
    done
}

#--------------------------------------------------{ Initialisation }---------------------------------------------------
trap bye INT TERM SIGINT SIGTERM EXIT
get_dimensions; stty -echo; printf "$COF"; clear
sec=$SECONDS # set timer for FPS counter
OBJ=(); game

