#!/usr/bin/env bash
# check bash version
case ${BASH_VERSINFO[@]::2} in [1-3]' '[0-9][0-9]|[1-3]' '[0-9]|'4 '[0-1])
    echo -e "\nYour BASH is too short!) 4.2+ required to run this game, your is - ${BASH_VERSINFO[@]}"
    exit 1;;
esac
. ~/SCR/color
#------------------------{ Start opt }------------------------{ description }-----------------{ def. values }-----------
     enumber=0                                        # current enemy counter                      (0)
       enmax=100                                      # max number of akiens                       (10)
         CLD=30
         SKY=$DEF
         spd=0.01                                     # game\read speed                            (0.0001)
         OBJ=()                                       # start obj array
           L=0                                        # sprites animation counter
[[ -e ~/.piuconf ]] && . ~/.piuconf
#------------------------{ Aliens }-------------------------------------------------------------------------------------
#  ___
# ( o )
#  `¯´

small=("${SKY}_Z_  ${SKY}_Z_  ${RED}o$SKY"
       "${SKY}_Z_  ${RED}o    ${SKY}_Z_$SKY"
       "${RED}o    ${SKY}_Z_  ${SKY}_Z_$SKY"
       "${SKY}_Z_  ${SKY}_Z_  ${SKY}_Z_$SKY")

sprite_alien () {
    hight=3
    width=5
    mov && ENM[$i]="$type $OX $OY $SC $SM $CS $CL $AS $AL" || { unset ENM[$i]; ((enumber--)); return; }
    X1="\\e[$OY;$[SX+1]H" X2="\\e[$[OY+2];$[SX+1]H"
    cut "\\e[$OY;${SX}H$SKY"      '' "$X1"'_' '_'  '_'
    cut "\\e[$[OY+1];${SX}H$SKY"  '(' ${small[AS]} ')'
    cut "\\e[$[OY+2];${SX}H$SKY"  '' "$X2"'`' '¯'  '´'
}

#------------------------{ Clouds }-------------------------------------------------------------------------------------
#  ,-+.
# (    )
#  `+-´

function sprite_cloud1 {
    hight=3
    width=6
    mov && BG1[$i]="$type $OX $OY $SC $SM $CS $CL $AS $AL" || { unset BG1[$i]; return; }
    X1="\\e[$OY;$[SX+1]H" X2="\\e[$[OY+2];$[SX+1]H"
    cut "\\e[$OY;${SX}H$SKY"       '' "$X1"',' '-' '+' '.'
    cut "\\e[$[$OY+1];${SX}H$SKY"  '('     ' ' ' ' ' ' ' ' ')'
    cut "\\e[$[$OY+2];${SX}H$SKY"  '' "$X2"'`' '+' '-' '´'
}

#  ,-._..
# (      )
#  `-...´

function sprite_cloud2 {
    hight=3
    width=8
    mov && BG2[$i]="$type $OX $OY $SC $SM $CS $CL $AS $AL" || { unset BG2[$i]; return; }
    X1="\\e[$OY;$[SX+1]H" X2="\\e[$[OY+2];$[SX+1]H"
    cut "\\e[$OY;${SX}H$SKY"       '' "$X1"',' '-' '.' '_' '.' '.'
    cut "\\e[$[$OY+1];${SX}H$SKY"  '('         ' ' ' ' ' ' ' ' ' ' ' ' ')'
    cut "\\e[$[$OY+2];${SX}H$SKY"  '' "$X2"'`' '-' '.' '.' '.' '´'
}

#  ,-¯`.-¯`.
# (         )
#  `--.,,.-´

function sprite_cloud3 {
    hight=3
    width=11
    mov && BG3[$i]="$type $OX $OY $SC $SM $CS $CL $AS $AL" || { unset BG3[$i]; return; }
    X1="\\e[$OY;$[SX+1]H" X2="\\e[$[OY+2];$[SX+1]H"
    cut "\\e[$OY;${SX}H$SKY"       '' "$X1"',' '-' '¯' '`' '.' '-' '¯' '`' '.'
    cut "\\e[$[$OY+1];${SX}H$SKY"  '('     ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ')'
    cut "\\e[$[$OY+2];${SX}H$SKY"  '' "$X2"'`' '-' '-' '.' ',' ',' '.' '-' '´'
}

#------------------------{ Functions }----------------------------------------------------------------------------------
get_dimensions () {
    size=( $(stty size) )
    endx=${size[1]}
    endy=${size[0]}
enmyendy=$[endy-7]
}

bye () { stty echo; printf "$CON$DEF"; exit $1; }
cut () { screen+="$1"; shift; printf -v spr %s "${@:$CS:$CL}"; screen+="${spr//_Z_/ }$SKY "; }
mov () {
    [[ $OX -le -$width ]]    && return 1
    case $SC in
        0) [[ $OX -le 0   ]] && ((CS++)); ((OX--)); ((CL++)); SC=$SM
           [[ $AS -ge $AL ]] &&   AS=0 || ((AS++));; # sprites animation;;
        *) [[ $SC -gt 0   ]] && ((SC--));;
    esac
    SX=${OX//-*/0} # SX'll be sprite's X coordinate, if OX less then 0 make it 0
}

get_obj_data () {
    type=${OI[0]} # object type
    OX=${OI[1]}   # X coordinate
    OY=${OI[2]}   # Y coordinate
    SC=${OI[3]}   # speed couter
    SM=${OI[4]}   # speed max
    CS=${OI[5]}   # cuting start
    CL=${OI[6]}   # cuting lenght
    AS=${OI[7]}   # animation start
    AL=${OI[8]}   # animation lenght
    [[ $type ]] && sprite_$type
}

fps_counter () {
    [[ $SECONDS -gt $sec ]] && {
        FPS=$FPSC AVG+=($FPS)
        [[ $FPSL ]] || FPSL=$FPS
        [[ $FPS -gt $FPSM  ]] && FPSM=$FPS
        [[ $FPS -lt $FPSL  ]] && FPSL=$FPS
        (( ${#AVG[@]} == 5 )) && { avg="${AVG[@]}"; FPSA=$(( (${avg// /+})/5 )); AVG=(); }
        sec=$SECONDS
        FPSC=0
    } || ((FPSC++))
}

game () {
    #======================================{ Main game loop single or server team mode }================================
    while true; do
        #-{ Empty screen, count fps, set timings}-----------------------------------------------------------------------
        [[ $M -ge 10 ]] && M=0 || ((M++)) # enemies born rate
        read -t$spd -s -n1 input &> /dev/null
        ENM=("${ENM[@]}")
        BG1=("${BG1[@]}")
        BG2=("${BG2[@]}")
        BG3=("${BG3[@]}")
        screen=; fps_counter

        #-{ Add cloud }-------------------------------------------------------------------------------------------------
        case $[RANDOM % $CLD]:$[RANDOM % 3 + 1] in
            0:1) BG1+=("cloud1 $[endx+1] $[RANDOM % 10 + 2] 6 6 1 0 0 0");;
            0:2) BG2+=("cloud2 $[endx+1] $[RANDOM % 10 + 2] 4 4 1 0 0 0");;
            0:3) BG3+=("cloud3 $[endx+1] $[RANDOM % 10 + 2] 2 2 1 0 0 0");;
        esac

        #-{ Add aliens }--------------------------------------------------------------------------------------------
        [[ $enumber -lt $enmax && $M -eq 0 ]] && {
            ENM+=("alien $[endx+1] $[RANDOM%enmyendy+3] 0 $[RANDOM%2] 1 0 $[RANDOM%3] 3")
            ((enumber++))
        }

        #-{ Print FPS }-------------------------------------------------------------------------------------------------
        screen+="\e[$endy;2H${DEF}FPS:$RED$FPS ${DEF}max:$RED$FPSM ${DEF}low:$RED$FPSL ${DEF}avg:$RED$FPSA "

        #-{ Move bitplans }---------------------------------------------------------------------------------------------
        for i in ${!BG1[@]}; { OI=(${BG1[$i]}); get_obj_data; }
        for i in ${!BG2[@]}; { OI=(${BG2[$i]}); get_obj_data; }
        for i in ${!ENM[@]}; { OI=(${ENM[$i]}); get_obj_data; }
        for i in ${!BG3[@]}; { OI=(${BG3[$i]}); get_obj_data; }

        #-{ Print everything }------------------------------------------------------------------------------------------
        printf "$screen"
    done
}

#--------------------------------------------------{ Initialisation }---------------------------------------------------
trap bye INT TERM SIGINT SIGTERM EXIT
get_dimensions; stty -echo; printf "$COF"; clear
game

