#!/bin/bash
#--{ Start opt }--------------------------------------{ description }-------------------------{ def. values }-----------
     enumber=0                                        # current enemy counter                      (0)
       enmax=2                                        # max number of akiens                       (10)
       month=`date +'%m'`                             # get current month
         spd=0.0001                                   # game\read speed                            (0.0001)
          LX=1                                        # grass X counter

[[ -e ~/.piuconf ]] && . ~/.piuconf
. ~/SCR/color
case $month in
    0[1-4]|12)
        SKY=$DEF$bwht         # winter & early spring sky
        LND=$DEF$BLD$WHT$BWHT # winter & early spring land
        CLD=30                # winter & early spring clouds rnd
        TRE=50;;              # winter & early spring trees rnd

    0[5-8]   )
        SKY=$DEF$bcyn         # late spring & summer sky
        LND=$DEF$DIM$GRN$bgrn # late spring & summer land
        CLD=50                # late spring & summer clouds rnd
        TRE=20;;              # late spring & summer trees rnd

    09|1[0-1])
        SKY=$DEF$BCYN         # autumn sky
        LND=$DEF$DIM$YLW$BGRN # autumn land
        CLD=20                # autumn clouds rnd
        TRE=50;;              # autumn trees rnd
esac
#------------------------{ Functions }----------------------------------------------------------------------------------
bye () { stty echo; printf "$CON$DEF"; exit $1; }

fps_counter () {
    [[ $SECONDS -gt $sec ]] && {
        FPS=$FPSC AVG+=($FPS)
        [[ $FPSL ]] || FPSL=$FPS
        [[ $FPS -gt $FPSM  ]] && FPSM=$FPS
        [[ $FPS -lt $FPSL  ]] && FPSL=$FPS
        (( ${#AVG[@]} == 5 )) && { avg="${AVG[@]}"; FPSA=$(( (${avg// /+})/5 )); AVG=(); }
        sec=$SECONDS
        FPSC=0
    } || ((FPSC++))
}

get_dimensions () {
    size=( $(stty size) )
    endx=${size[1]}
    endy=${size[0]}
enmyendy=$[endy-7]
boomendx=$[endx-10]
bullendx=$[endx-4 ]
heroendx=$[endx-15]
heroendy=$[endy-7 ]
enmyendy=$[endy-7 ]
bossendx=$[endx-11]
bossendy=$[endy-7 ]
bosshbar=$[endx-10]
lineendy=$[endy-2 ]
Sunsendx=$[endx-18]
cratendx=$[endx-7 ]
cratendy=$[endy-7 ]
tre1endy=$[endy-tree1H-2]
tre2endy=$[endy-tree2H-2]
tre3endy=$[endy-tree3H-2]
}

print_sprite () {
    OT=${OI[0]}   # object type
    OX=${OI[1]}   # X coordinate
    OY=${OI[2]}   # Y coordinate
    OH=${OI[3]}   # object hight
    OW=${OI[4]}   # object width
    SC=${OI[5]}   # speed counter
    SM=${OI[6]}   # speed max
    CS=${OI[7]}   # cuting start
    CL=${OI[8]}   # cuting lenght
    AS=${OI[9]}   # animation start
    AL=${OI[10]}  # animation lenght
    C1=${OI[11]}  # custom obj parameter 1
    C2=${OI[12]}  # custom obj parameter 2
    [[ $OT ]] && sprite_$OT
}

mov () {
    case $SC in
        0) [[ $OX -le -$OW ]] && return 1
           [[ $AS -ge  $AL ]] && AS=0 || ((AS++))
           [[ $OX -le  1   ]] && ((CS++))
           ((OX--)); ((CL++)); SC=$SM;;
        *) ((SC--));;
    esac
    [[ $OX -le 1 ]] && SX=0 || SX=$OX
}

fill_screen () {
    for ((i=0;         i<$lineendy; i++)); do printf "$SKY%${endx}s"; done
    for ((i=$lineendy; i<$endy;     i++)); do printf "$LND%${endx}s"; done
}

cut () {
    xcord=$1 ycord=$2 color=$3; shift 3
    screen+="\e[$ycord;${xcord}H$color"
    printf -v spr %s "${@:$CS:$CL}"
    spr="${spr//_Y_/'\e['$ycord;}"
    screen+="${spr//_Z_/ }"
}

movy () {
    case $SC in
        0) [[ $OY -ge $[endy-2] ]]    && return 1
           [[ $AS -ge $AL  ]] && AS=0 || ((AS++))
           [[ $CS -le $OH  ]] && ((CS++))
           ((OY++)); SC=$SM;;
        *) ((SC--));;
    esac
}

cuty () {
    xcord=$1 ycord=$2 cuter=$3; shift 3
    [[ $CS -ge $cuter ]] && screen+="\e[$[ycord-cuter];${xcord}H$@"
}

sprite_crate () {
    movy && ENM[$i]="crate $OX $OY $OH $OW $SC $SM $CS $CL" || unset ENM[$i]
    CM1=$SKY$ylw CM2=$SKY$blk CM3=$SKY$BLU SS="$RED ? $CM3"
    ########################1234567###01234567
    cuty  $OX    $OY 7 $SKY'       ' #1       
    cuty  $OX    $OY 6 $CM1' ¸.—.¸ ' #2 ¸.—.¸ 
    cuty  $OX    $OY 5 $CM1'(︹_︹)'  #3(︹_︹)
    cuty $[OX+1] $OY 4  $CM2'╲╱ ╲╱'  #4 ╲╱ ╲╱ 
    cuty $[OX+1] $OY 3  $CM3'╔╧╦╧╗'  #5 ╔╧╦╧╗ 
    cuty $[OX+1] $OY 2  $CM3"╠$SS╣"  #6 ╠ ? ╣ 
    cuty $[OX+1] $OY 1  $CM3'╚═╩═╝'  #7 ╚═╩═╝ 
}

sprite_alien () {
    mov && ENM[$i]="alien $OX $OY $OH $OW $SC $SM $CS $CL $AS $AL" || { unset ENM[$i]; ((enumber--)); return; }
    CM1=$SKY$RED CM2=$SKY$BLK CM3=$SKY$BLD$WHT X1=_Y_$[OX+1]H X2=_Y_$[OX+5]H X3=_Y_$[OX+9]H X4=_Y_$[OX+10]H
    #0123456789ABC
    #1 /   |   \  
    #2<    |    > 
    #3 \   |   /  
    #################### 1       2    3   4   5          6       7       8       9         A          B   C  #0
    cut $SX  $OY    $CM1 ''  $X1'/'  ' ' ''  ''  $X2$CM2'|'     ' '     ''      '' $X3$CM3'\\'       ' '     #1
    cut $SX $[OY+1] $CM1 '<'    '-'  '-' '-' '-' $X2$CM2'+' $CM3'-' $CM3'-' $CM3'-'   $CM3'-' $X4$CM3'>' ' ' #2
    cut $SX $[OY+2] $CM1 ''  $X1'\\' ' ' ''  ''  $X2$CM2'|'     ' '     ''      '' $X3$CM3'/'        ' '     #3
}

game () {
    #======================================{ Main game loop single or server team mode }================================
    while true; do
        #-{ Empty screen, count fps, set timings}------------------------------
        [[ $M -ge 10 ]] && M=0 || ((M++)) # enemies born rate
        read -t$spd -s -n1 input &> /dev/null
        ENM=("${ENM[@]}")
        screen=; fps_counter

        #-{ Add aliens }-------------------------------------------------------
        [[ $enumber -lt $enmax && $M -eq 0 ]] && {
            ENM+=("alien $endx $[RANDOM%enmyendy+3] 3 12 0 $[RANDOM%3]   1 0 $[RANDOM%3] 3")
            ENM+=("crate $[1+RANDOM%(endx-8)] 5     7 7  0 $[RANDOM%5+5] 0")
            ((enumber++))
        }

        #-{ Print FPS }--------------------------------------------------------
        screen+="\e[$endy;2H${DEF}FPS:$RED$FPS ${DEF}max:$RED$FPSM ${DEF}low:$RED$FPSL ${DEF}avg:$RED$FPSA "

        for i in ${!ENM[@]}; { OI=(${ENM[$i]}); print_sprite; }

        #-{ Print everything }-------------------------------------------------
        printf "$screen"
#        echo -e "\\e[$[endy-2];1H${ENM[@]}  "
    done
}

#=================================================={ Initialisation }===================================================
trap : ALRM
trap bye INT TERM SIGINT SIGTERM EXIT
get_dimensions; stty -echo; printf "$COF"; clear
fill_screen; game

