#!/bin/bash
target=../piu-piu
sed -n '1,/_FUNCTIONS_/p' main    >  $target
sed '1d' functions                >> $target
sed '1d' messages                 >> $target
sed '1d' sprites                  >> $target
sed -n '/_SPRITES_/,$p'   main    >> $target
sed -i '/_SPRITES_/d;/_FUNCTIONS_/d;/_MESSAGES_/d' $target
chmod +x $target
