#!/bin/bash
[[ $penis ]] && {

heroendx=$[endx-15]
heroendy=$[endy-9 ]

enl1=('' ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─)
enl2=('' _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _)
enl3=('' ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕ ⎕)
sprite_penis1 () {
    mov - || { unset HER[i];  return; }
    [[ $1 ]] || control_hero1 $H1X $H1Y
    if [[ $life -gt 0 ]]; then
       OX=$H1X OY=$H1Y CS=1 CL=$[16+G]
    else # when hero's health goes to 0 it starts to fall, explodes and bounces on the ground
       AS=0 SM=3  #spd=0.1
       [[ $OY -lt $TY ]] && ((OY++))  || { TY=$[heroendy-C2+2]; ((C2--)); }
       [[ $OY -gt $TY ]] && ((OY--))  ||   TY=$[heroendy+2]
       [[ $OX -gt -10 && $C1 -eq 0 ]] && { BOOM $SX $[OY-2]; C1=15; }
       screen+="\\e[$[endy-1];$[OX+OW]H$LND "
    fi

    case $type in
     'duel')
         re="crate ($[OX+6+G]|$[OX+7+G]|$[OX+8+G]|$[OX+9+G]|$[OX+10+G]) ($[OY+2]|$[OY+3]|$[OY+4]|$[OY+5]|$[OY+6]).*";;
     'team')
         re="(life|ammo|gunup) ($[OX+11+G]|$[OX+12+G]) ($[OY+1]|$[OY+2]|$[OY+3]|$[OY+4]).*|"
        re+="alien ($[OX+11+G]|$[OX+12+G]) ($[OY+1]|$[OY+2]).*|alien ($[OX+6]|$[OX+7]) ($[OY+3]|$[OY+4]).*|"
        re+="bfire ($[OX+11+G]|$[OX+12+G]) ($[OY+2]|$[OY+3]).*|bfire ($[OX+6]|$[OX+7]) ($[OY+3]|$[OY+4]).*|"
        re+="boss ($[OX+11+G]|$[OX+12+G]) $[OY-1].*";;
    esac

    T1=${shoot[AS]}; local x1=$OX x2=$SX
    CM1=$SKY$H1C$BLD CM2=$SKY$DIM$H1C CM3=$SKY$S1C
    ((AS<=1)) && ((x1--))
    ((x2< 1)) && x2=1; [[ $1 ]] && ((x1++)); X2="_Y_$[x2+2]H" X3="_Y_$[x1-1]H" X4="_Y_$[x2+10+G]H"
    #00000000001111111#0
    #01234567890123456#0
    #1                #1
    #2   _____ _____  #2
    #3    .-──╨──▅▃   #3
    #4 -=╳ ______▜▉▉▖ #4
    #5   / |\     ▔▔  #5
    #6  (__)_)        #6
    #7                #7    0  0     0     0 0  0      0      0     0 1  1                   1     1     1     1 1 #0
    ######X####Y####CLR#    1  2     3     4 5  6      7      8     9 0  1                   2     3     4     5 6 #0
    cut $SX  $OY    $SKY    '' '' $X2⎕     ⎕ ⎕  ⎕      ⎕      ⎕     ⎕ ⎕  ⎕                   ⎕     ⎕     ⎕     ⎕   #1
    cut $SX $[OY+1] $CM1    '' '' $X2⎕                       ${mainrotor[AS]}                    ${enl3[@]:1:$G}   #2
    cut $SX $[OY+2] $CM1    ⎕  ⎕     ⎕     ⎕ .  -      ─      ─     ╨ ─  ${enl1[@]:1:$G} $CM3▅     ▃ $SKY⎕     ⎕ ⎕ #3
    cut $SX $[OY+3] $CM2    ⎕    $T1   $CM2╳ ⎕  _      _      _     _ _  ${enl2[@]:1:$G} $CM3▜     ▉     ▉     ▖ ⎕ #4
    cut $SX $[OY+4] $CM2    ⎕  ⎕     ⎕     / ⎕ \| $CM1\\      ⎕ $SKY⎕ ⎕  ${enl3[@]:1:$G}     ⎕ $CM3▔     ▔ $SKY⎕ ⎕ #5
    cut $SX $[OY+5] $CM2 $X3⎕  ⎕    \(     _ _ \)      _ $CM1\)     ⎕ ⎕  ''               $X4⎕     ⎕     ⎕     ⎕   #6
    cut $SX $[OY+6] $SKY $X3⎕  ⎕     ⎕     ⎕ ⎕  ⎕      ⎕      ⎕     ⎕ ⎕                                            #7

    [[  $C1 -gt 0 ]]  && ((C1--))
    collision 1 "$re" && { BOOM $OX $OY; ((life--)); }
    HER[i]="penis1 $OX $OY 7 $[16+G] $SC $SM $CS $CL $AS $AL $C1 $C2"
}

sprite_penis2 () {
    mov - || { unset HER[i]; return; }
    if [[ $life2 -gt 0 ]]; then
        CS=1 CL=16 OX=$H2X OY=$H2Y
        [[ $penis ]] && CL=$[15+G]
    else # when heros health goes to 0 it starts to fall, explodes and bounces on the ground
        AS=0 SM=3 H2Y=
        [[ $OY -lt $TY ]] && ((OY++))  || { TY=$[heroendy-C2+2]; ((C2--)); }
        [[ $OY -gt $TY ]] && ((OY--))  ||   TY=$[heroendy+2]
        [[ $OX -gt -10 && $C1 -eq 0 ]] && { BOOM $SX $[OY-2]; C1=15; }
        screen+="\\e[$[endy-1];$[OX+OW]H$LND "
    fi

    T1=${shoot[AS]}; local x1=$OX x2=$SX
    CM1=$SKY$H2C$BLD CM2=$SKY$DIM$H2C CM3=$SKY$S2C
    ((AS<=1)) && ((x1--))
    ((x2< 1)) && x2=1; [[ $1 ]] && ((x1++))
    case $type in
     'duel') control_hero2 $[H2X-10] $H2Y
             re="crate ($[OX-4]|$[OX-3]|$[OX-2]|$[OX-1]|$OX) ($[OY+2]|$[OY+3]|$[OY+4]|$[OY+5]|$[OY+6]).*"
             X1="_Y_$[x2+1]H" X2="_Y_$[x1+5+G2]H" X3="_Y_$[x2+G2]H"
             #00000000001111111#0
             #01234567890123456#0
             #1                #1
             #2  _____ _____   #2
             #3   ▃▅──╨──-.    #3
             #4 ▗▉▉▛______ ╳=- #4
             #5  ▔▔     /| \   #5
             #6        (_(__)  #6
             #7                #7  0     0  0  0     0                    0     0 0  0     1  1 1      1      1  1 1 #0
             ######X####Y#####CLR# 1     2  3  4     5                    6     7 8  9     0  1 2      3      4  5 6 #0
             cut $SX  $OY    $SKY  '' $X3⎕  ⎕  ⎕     ⎕                    ⎕     ⎕ ⎕  ⎕     ⎕  ⎕ ⎕      ⎕             #1
             cut $SX $[OY+1] $CM1  '' $X1${enl3[@]:1:$G2}                  ${mainrotor[AS]}            ⎕             #2
             cut $SX $[OY+2] $CM3  ⎕     ⎕  ⎕  ▃     ▅ $CM2${enl1[@]:1:$G2}     ─ ╨  ─     ─  - .      ⎕      ⎕  ⎕ ⎕ #3
             cut $SX $[OY+3] $CM3  ⎕     ▗  ▉  ▉     ▛ $CM2${enl2[@]:1:$G2}     _ _  _     _  _ ⎕      ╳      $T1  ⎕ #4
             cut $SX $[OY+4] $CM3  ⎕     ⎕  ▔  ▔ $SKY⎕     ${enl3[@]:1:$G2}     ⎕ ⎕  ⎕ $CM2/ \| ⎕ $CM1\\      ⎕  ⎕ ⎕ #5
             cut $SX $[OY+5] $CM2  '' $X1⎕  ⎕  ⎕     ⎕                    '' $X2⎕ ⎕ \(     _ \( _      _ $CM1\)  ⎕ ⎕ #6
             cut $SX $[OY+6] $SKY  ''    '' '' ''    ''                   '' $X2⎕ ⎕  ⎕     ⎕  ⎕ ⎕      ⎕      ⎕  ⎕;; #7

     'team') control_hero2 $H2X $H2Y
             re="(life|ammo|gunup) ($[OX+11+G2]|$[OX+12+G2]) ($[OY+1]|$[OY+2]|$[OY+3]|$[OY+4]).*|"
             re+="alien ($[OX+11+G2]|$[OX+12+G2]) ($[OY+1]|$[OY+2]).*|alien ($[OX+6]|$[OX+7]) ($[OY+3]|$[OY+4]).*|"
             re+="bfire ($[OX+11+G2]|$[OX+12+G2]) ($[OY+2]|$[OY+3]).*|bfire ($[OX+6]|$[OX+7]) ($[OY+3]|$[OY+4]).*|"
             re+="boss ($[OX+11+G2]|$[OX+12+G2]) $[OY-1].*"

             X2="_Y_$[x2+2]H" X3="_Y_$[x1-1]H" X4="_Y_$[x2+10+G2]H"
             #00000000001111111#0
             #01234567890123456#0
             #1                #1
             #2   _____ _____  #2
             #3    .-──╨──▅▃   #3
             #4 -=╳ ______▜▉▉▖ #4
             #5   / |\     ▔▔  #5
             #6  (__)_)        #6
             #7                #7    0  0     0     0 0  0      0      0     0 1  1                    1     1     1     1 1 #0
             ######X####Y####CLR#    1  2     3     4 5  6      7      8     9 0  1                    2     3     4     5 6 #0
             cut $SX  $OY    $SKY    '' '' $X2⎕     ⎕ ⎕  ⎕      ⎕      ⎕     ⎕ ⎕  ⎕                    ⎕     ⎕     ⎕     ⎕   #1
             cut $SX $[OY+1] $CM1    '' '' $X2⎕                       ${mainrotor[AS]}                     ${enl3[@]:1:$G2}  #2
             cut $SX $[OY+2] $CM1    ⎕  ⎕     ⎕     ⎕ .  -      ─      ─     ╨ ─  ${enl1[@]:1:$G2} $CM3▅     ▃ $SKY⎕     ⎕ ⎕ #3
             cut $SX $[OY+3] $CM2    ⎕    $T1   $CM2╳ ⎕  _      _      _     _ _  ${enl2[@]:1:$G2} $CM3▜     ▉     ▉     ▖ ⎕ #4
             cut $SX $[OY+4] $CM2    ⎕  ⎕     ⎕     / ⎕ \| $CM1\\      ⎕ $SKY⎕ ⎕  ${enl3[@]:1:$G2}     ⎕ $CM3▔     ▔ $SKY⎕ ⎕ #5
             cut $SX $[OY+5] $CM2 $X3⎕  ⎕    \(     _ _ \)      _ $CM1\)     ⎕ ⎕  ''                $X4⎕     ⎕     ⎕     ⎕   #6
             cut $SX $[OY+6] $SKY $X3⎕  ⎕     ⎕     ⎕ ⎕  ⎕      ⎕      ⎕     ⎕ ⎕                                             #7
     esac

     [[ $C1 -gt 0   ]] && ((C1--))
     collision 2 "$re" && { BOOM $OX $OY; ((life2--)); }
     HER[i]="penis2 $OX $OY 7 $[15+G2] $SC $SM $CS $CL $AS $AL $C1 $C2"
}

#------------------------{ Shoots }-------------------------------------------------------------------------------------
case "$day:$month" in
      *:[01][1-4]) CM1=$SKY$BLD$CYN;;
                *) CM1=$SKY$BLD$WHT;;
esac
cumback=(              # ● ⊕ ⊙ ○
    "${CM1}— ${CM1}‾"  # ○‾— ○—‾
    "${CM1}— ${CM1}—"  # ○—— ○‾—
    "${CM1}— ${CM1}_"  # ○_— ○—_
    "${CM1}— ${CM1}—") # ○—— ○_—
cum=(                  # ● ⊕ ⊙ ○
    "${CM1}‾ ${CM1}—"  # ‾—○ —‾○
    "${CM1}— ${CM1}—"  # ——○ ‾—○
    "${CM1}_ ${CM1}—"  # _—○ —_○
    "${CM1}— ${CM1}—") # ——○ _—○

sprite_piu1 () {
    case $type in
        'duel') re="${ht}2 ($OX|$[OX+1]) ($[OY-1]|$[OY-2]|$[OY-3]|$[OY-4]).*";;
        'team') re="alien ($OX|$[OX+1]) $[OY-1].*|boss ($OX|$[OX+1]) ($[OY-2]|$[OY-3]|$[OY-4]).*";;
    esac;  mov + && PIU[i]="piu1 $OX $OY 1 4 $SC $SM $CS $CL $AS 3" || { unset PIU[i]; return; }

    case "$day:$month" in
          *:[01][1-4]) CM1=$SKY$BLD$CYN;;
                    *) CM1=$SKY$BLD$WHT;;
    esac

    #01234
    #1 —_○
    ################  1    2    3       4 #0
    cut $OX $OY $SKY ' ' ${cum[AS]} $CM1○ #1
    collision 1 "$re" $OX $[OY-1] && unset PIU[i]
}

sprite_piu2 () {
    case $type in
         'duel') direction='-' re="${ht}1 ($[OX-9-G]|$[OX-10-G]) ($[OY-1]|$[OY-2]|$[OY-3]|$[OY-4]).*";;
         'team') direction='+' re="alien ($OX|$[OX+1]) $[OY-1].*|boss ($OX|$[OX+1]) ($[OY-2]|$[OY-3]|$[OY-4]).*";;
    esac;   mov $direction && PIU[i]="piu2 $OX $OY 1 4 $SC $SM $CS $CL $AS 3" || { unset PIU[i]; return; }

    case "$day:$month" in
          *:[01][1-4]) CM1=$SKY$BLD$CYN;;
                    *) CM1=$SKY$BLD$WHT;;
    esac

    case "$type" in
         'duel')
                 #01234
                 #1○—_
                 ################  1      2    3       4   #0
                 cut $SX $OY $CM1 '○' ${cumback[AS]} $SKY⎕;; #1

              *) #01234
                 #1 —_○
                 ################ 1   2   3        4   #0
                 cut $OX $OY $SKY ⎕ ${cum[AS]} $CM1○;; #1
    esac;        collision 2 "$re" $OX $[OY-1] && unset PIU[i]
}

} # the end of the penis (the tip)